### ISSUE TITLE
Create dataset loader for WikiANN

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#1]
Dataloader name: `wikiann/wikiann.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?wikiann

|     Dataset| wikiann |
|-------------|---|
| Description | WikiANN (sometimes called PAN-X) is a multilingual named entity recognition dataset consisting of Wikipedia articles annotated with LOC (location), PER (person), and ORG (organisation) tags in the IOB2 format. This version corresponds to the balanced train, dev, and test splits of Rahimi et al. (2019), which supports 176 of the 282 languages from the original WikiANN corpus. |
| Subsets | id, jv, my, tl, th, vi, km, su |
| Languages | ind, jav, mya, tgl, tha, vie, khm, sun |
| Tasks | Named Entiy Recognition |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/panx27/wikiann |
| HF URL | https://huggingface.co/datasets/wikiann |
| Paper URL | https://aclanthology.org/P19-1015/ |

**Comment by muhsatrio** [comment]
#self-assign

**Comment by muhsatrio** [comment]
#self-assign
