### ISSUE TITLE
Create dataset loader for Beaye Lexicon

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#10]
Dataloader name: `beaye_lexicon/beaye_lexicon.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?beaye_lexicon

|     Dataset| beaye_lexicon |
|-------------|---|
| Description | The Beaye Lexicon is a lexicon resource encompassing translations between Indonesian, English, and Beaye words. Developed through a collaborative effort involving two native Beaye speakers and evaluated by linguistic experts, this lexicon comprises 984 Beaye vocabularies. The creation of the Beaye Lexicon marks the inaugural effort in documenting the previously unrecorded Beaye language. |
| Subsets | lexicon |
| Languages | day |
| Tasks | Word lists |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/joanitolopo/bhinneka-korpus/tree/main/lexicon |
| HF URL | - |
| Paper URL | https://drive.google.com/file/d/1AMWTvzhSyOf0kK89E8xbhsx34kwa-4dZ/view?usp=drivesdk |

**Comment by joanitolopo** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @joanitolopo , may I know the current status of this dataloader creation? Feel free to discuss in here if you have any difficulties, thx!

**Comment by holylovenia** [comment]
Hi @joanitolopo, we received no response from you regarding this dataloader, so I will remove your assignment.

Anyone who is interested in taking this dataloader, please feel free to `#self-assign`.

**Comment by joanitolopo** [comment]
#self-assign

**Comment by joanitolopo** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @joanitolopo, thanks for re-taking this again. A completion ETA for this task would be very helpful, mind adding that?

**Comment by joanitolopo** [comment]
Yeah of course, I will be pull and request in this Saturday, I hope.

**Comment by joanitolopo** [comment]
I would like to ask about the Supported Task in Beaye Lexicon. The dataset is only the word list containing ID-ENG_DAY word pairs, so what is the best choice for the supported task?

**Comment by sabilmakbar** [comment]
Apologies for this. I think this doesn't supported in SEACrowd, nor it will be supported in the future since it only contains a Word-list, not a sentence or longer that can be attributed to MT task.

Any comments on this, @holylovenia @SamuelCahyawijaya?

**Comment by holylovenia** [comment]
Hi @joanitolopo, sorry for the late reply. For word lists, we only need to implement the `source` schema. Could you please take a look at the [Toxicity-200](https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/sea_datasets/toxicity_200/toxicity_200.py) dataloader as an example?

Feel free to let us know if you have any questions.

**Comment by joanitolopo** [comment]
Okay, thankyou very much for the reply. 

May i ask something @holylovenia . I got an error like this:  `ValueError: BuilderConfig beaye_lexicon_source not found. Available: ['beaye_lexicon_ind_source', 'beaye_lexicon_day_source']` when i run the unit test, eventhought i have already declared the DEFAULT_CONFiG_NAME = "beaye_lexicon_ind_source"

**Comment by sabilmakbar** [comment]
you may try using this one:

`python -m tests.test_seacrowd_source_only seacrowd/sea_datasets/beaye_lexicon/beaye_lexicon.py --subset_id beaye_lexicon_ind`

1. use `test_seacrowd_source_only` instead of `test_seacrowd` since you don't implement SEACrowd schema
2. use `subset_id` args so that the config will be constructed into `beaye_lexicon_ind_source` instead of not passing it and leading to incorrect construction of `beaye_lexicon_source`

**Comment by sabilmakbar** [comment]
Hi @joanitolopo, you may have a look at the latest suggestion and see if it makes your dataloader pass the test cases defined (and let us know if you encounter another problem if it doesn't). Thanks!

**Comment by joanitolopo** [comment]
I have tested, and it works. Thank you for help

Pada Sab, 6 Jan 2024 22.35, Salsabil Maulana Akbar ***@***.***>
menulis:
