### ISSUE TITLE
Create dataset loader for THAI SER

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#102]
Dataloader name: `thai_ser/thai_ser.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_ser

|     Dataset| thai_ser |
|-------------|---|
| Description | THAI SER dataset consists of 5 main emotions assigned to actors: Neutral, Anger, Happiness, Sadness, and Frustration. The recordings were 41 hours, 36 minutes long (27,854 utterances), and were performed by 200 professional actors (112 female, 88 male) and directed by students, former alumni, and professors from the Faculty of Arts, Chulalongkorn University.  The THAI SER contains 100 recordings and is separated into two main categories: Studio and Zoom. Studio recordings also consist of two studio environments: Studio A, a controlled studio room with soundproof walls, and Studio B, a normal room without soundproof or noise control. |
| Subsets | - |
| Languages | tha |
| Tasks | Speech Emotion Recognition |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/vistec-AI/dataset-releases/releases/tag/v1 |
| HF URL | - |
| Paper URL | https://airesearch.in.th/releases/speech-emotion-dataset/ |

**Comment by bp-high** [comment]
#self-assign

**Comment by bp-high** [comment]
Yep working on this issues got busy with some things but will try to wrap this issues by next week.

**Comment by holylovenia** [comment]
Okay then, @bp-high. Feel free to let us know if you need any help!

**Comment by bp-high** [comment]
Sorry couldn't work on this last weekend due to christmas holidays and celebration. Working on concluding the issue by this week.

**Comment by holylovenia** [comment]
@bp-high No problem! Just let us know if you need some help.

**Comment by zwenyu** [comment]
#self-assign
