### ISSUE TITLE
Create dataset loader for Software Documentation Data Set for Machine Translation

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#103]
Dataloader name: `sap_wat/sap_wat.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?sap_wat

|     Dataset| sap_wat |
|-------------|---|
| Description | The data set originates from the SAP Help Portal that contains documentation for SAP products and user assistance for product-related questions. The data has been processed in a way that makes it suitable as development and test data for machine translation purposes. The current language scope is English to Hindi, Indonesian, Japanese, Korean, Malay, Thai, Vietnamese, Simplified Chinese and Traditional Chinese. For each language pair about 4k segments are available, split into development and test data. The segments are provided in their document context and are annotated with additional metadata from the document. |
| Subsets | EN-ID, EN-TH, EN-MS, EN-VI |
| Languages | eng, ind, zlm, tha, vie |
| Tasks | Machine Translation |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/SAP/software-documentation-data-set-for-machine-translation |
| HF URL | - |
| Paper URL | https://aclanthology.org/2020.wat-1.20/ |

**Comment by yana-xuyan** [comment]
#self-assign
