### ISSUE TITLE
Create dataset loader for Filipino Product Reviews (Lazada)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#104]
Dataloader name: `lazada_review_filipino/lazada_review_filipino.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?lazada_review_filipino

|     Dataset| lazada_review_filipino |
|-------------|---|
| Description | The dataset contains over 900+ weakly annotated Filipino reviews scraped from the Lazada Philippines platform. Each review is associated with a five star point rating where one is the lowest and five is the highest. |
| Subsets | - |
| Languages | fil, tgl |
| Tasks | Sentiment Analysis |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/EricEchemane/Filipino-Tagalog-Product-Reviews-Sentiment-Analysis/tree/main/data |
| HF URL | - |
| Paper URL | https://github.com/EricEchemane/Filipino-Tagalog-Product-Reviews-Sentiment-Analysis/tree/main |

**Comment by bp-high** [comment]
#self-assign

**Comment by bp-high** [comment]
Yep working on this issues got busy with some things but will try to wrap this issues by next week.

**Comment by sabilmakbar** [comment]
I'll un-stale this for now. Please do add a tag `pr-ready` whenever you have finished on your dataloader so that the bot won't tag this issue as stale or let us know if you need more time for this issue.

**Comment by bp-high** [comment]
Sorry couldn't work on this last weekend due to christmas holidays and celebration will try to conclude this, this weekend.

**Comment by sabilmakbar** [comment]
Thanks for the update, @bp-high! no rush on this; please take your time to enjoy ur holiday!

**Comment by sabilmakbar** [comment]
Hi @bp-high, may we know the update on this dataloader issue? It's been 3 weeks since the last poke from the SEACrowd stale-checker, and we might consider unassigning if there's no progress update in the next 24 hours.
