### ISSUE TITLE
Create dataset loader for NewsPH

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#106]
Dataloader name: `newsph/newsph.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?newsph

|     Dataset| newsph |
|-------------|---|
| Description | Raw collection of news articles in Filipino which can be used for language modelling. |
| Subsets | - |
| Languages | tgl, fil |
| Tasks | Language Modeling |
| License | GNU General Public License v3.0 (gpl-3.0) |
| Homepage | https://huggingface.co/datasets/newsph |
| HF URL | https://huggingface.co/datasets/newsph |
| Paper URL | https://arxiv.org/abs/2010.11574 |

**Comment by IvanHalimP** [comment]
#self-assign
