### ISSUE TITLE
Create dataset loader for Fake News Filipino

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#107]
Dataloader name: `fakenews_ph/fakenews_ph.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?fakenews_ph

|     Dataset| fakenews_ph |
|-------------|---|
| Description | Fake news articles were sourced from online sites that were tagged as fake news sites by the non-profit independent media fact-checking organization Verafiles and the National Union of Journalists in the Philippines (NUJP). Real news articles were sourced from mainstream news websites in the Philippines, including Pilipino Star Ngayon, Abante, and Bandera. |
| Subsets | - |
| Languages | fil |
| Tasks | Hoax Detection |
| License | Unknown (unknown) |
| Homepage | https://github.com/jcblaisecruz02/Tagalog-fake-news |
| HF URL | https://huggingface.co/datasets/fake_news_filipino |
| Paper URL | https://aclanthology.org/2020.lrec-1.316/ |

**Comment by ljvmiranda921** [comment]
#self-assign
