### ISSUE TITLE
Create dataset loader for Asian Language Treebank Parallel Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#109]
Dataloader name: `parallel_asian_treebank/parallel_asian_treebank.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?parallel_asian_treebank

|     Dataset| parallel_asian_treebank |
|-------------|---|
| Description | The ALT project aims to advance the state-of-the-art Asian natural language processing (NLP) techniques through the open collaboration for developing and using ALT. The process of building ALT began with sampling about 20,000 sentences from English Wikinews, and then these sentences were translated into the other languages. ALT now has 13 languages, including 8 languages spoken in Southeast Asia: Filipino, Bahasa Indonesia, Khmer, Lao, Malay, Myanmar (Burmese), Thai, and Vietnamese. |
| Subsets | - |
| Languages | khm, lao, mya, ind, fil, zlm, tha, vie |
| Tasks | Machine Translation |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/ |
| HF URL | - |
| Paper URL | https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/ALT-Parallel-Corpus-20191206/ALT-O-COCOSDA.pdf |

**Comment by muhsatrio** [comment]
#self-assign
