### ISSUE TITLE
Create dataset loader for WikiMatrix

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#110]
Dataloader name: `wikimatrix/wikimatrix.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?wikimatrix

|     Dataset| wikimatrix |
|-------------|---|
| Description | WikiMatrix is automatically extracted parallel sentences from the content of Wikipedia articles in 96 languages, including several dialects or low-resource languages. 8 languages among them are spoken in Southeast Asia region. In total, there are 135M parallel sentences from 1620 different language pairs. |
| Subsets | There are 60 language pairs subsets involving low-resource languages (ilo-ca, ilo-da, ilo-de, ..., ceb-ru, ceb-zh) and 171 languages pairs subsets involving Indonesian, Tagalog, or Vietnamnese |
| Languages | ilo, min, jav, sun, ceb, ind, tgl, vie |
| Tasks | Machine Translation |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/facebookresearch/LASER/tree/main/tasks/WikiMatrix |
| HF URL | - |
| Paper URL | https://aclanthology.org/2021.eacl-main.115/ |

**Comment by yana-xuyan** [comment]
#self-assign

**Comment by yana-xuyan** [comment]
Hi @holylovenia @SamuelCahyawijaya @sabilmakbar, just for your information, the language pairs involving `ilo` and `min` are not available in this dataset. Based on the caption of Table 5 in the corresponding paper, it seems like the authors filtered out those data samples, as it writes, "Alignments with other languages yield less than 5k sentences and are omitted for clarity.".

**Comment by yana-xuyan** [comment]
Sorry, Sundanese is also not included.
