### ISSUE TITLE
Create dataset loader for Thai Constitution Dataset

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#111]
Dataloader name: `thai_constitution/thai_constitution.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_constitution

|     Dataset| thai_constitution |
|-------------|---|
| Description | A collection of snippets from the Thai constitution from 1932 and retrieved from the Thai Office of the Council of State (http://www.krisdika.go.th/). |
| Subsets | - |
| Languages | tha |
| Tasks | Language Modeling, Language Identification |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/PyThaiNLP/Thai-constitution-corpus/tree/master/data |
| HF URL | - |
| Paper URL | https://github.com/PyThaiNLP/Thai-constitution-corpus/tree/master/data |

**Comment by ilhamfp** [comment]
#self-assign

Curious what schema/task would this falls into? Self-supervised pretraining?

**Comment by ilhamfp** [comment]
#self-assign

**Comment by ilhamfp** [comment]
Currently drafting a PR :)
