### ISSUE TITLE
Create dataset loader for Wisesight Thai Sentiment Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#112]
Dataloader name: `wisesight_thai_sentiment/wisesight_thai_sentiment.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?wisesight_thai_sentiment

|     Dataset| wisesight_thai_sentiment |
|-------------|---|
| Description | This dataset comprises 26,737 Thai social media texts from 2016 to early 2019, primarily informal and conversational, including some news headlines and advertisements. It is split across positive, negative, and neutral sentiments. The content mainly relates to consumer products and services, with a portion on current affairs. It includes only publicly available internet messages, specifically public comments on Facebook pages. Private communications and group messages are excluded. The corpus doesn't statistically represent any language register, contains modifications like personal data removal, and maintains original (mis)spellings and emojis. Messages over 2,000 characters, non-Thai, or duplicates are omitted. |
| Subsets | - |
| Languages | tha |
| Tasks | Sentiment Analysis, Aspect Based Sentiment Analysis |
| License | Creative Commons Zero v1.0 Universal (cc0-1.0) |
| Homepage | https://github.com/PyThaiNLP/wisesight-sentiment |
| HF URL | - |
| Paper URL | https://github.com/PyThaiNLP/wisesight-sentiment |

**Comment by bp-high** [comment]
#self-assign

**Comment by bp-high** [comment]
HF Dataset link:- https://huggingface.co/datasets/wisesight_sentiment

**Comment by bp-high** [comment]
#self-assign

**Comment by pavaris-pm** [comment]
@bp-high do you currently working on this? if not, maybe I will assign myself to handle this dataset for dataloader creation instead.

**Comment by pavaris-pm** [comment]
#self-assign

**Comment by bp-high** [comment]
Hi @pavaris-pm I am thinking of finishing this task this weekend, If I am not able to do this by this weekend I will inform you and you can feel free to pick this up then.
