### ISSUE TITLE
Create dataset loader for VnDT: A Vietnamese dependency treebank

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#114]
Dataloader name: `vndt/vndt.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vndt

|     Dataset| vndt |
|-------------|---|
| Description | VnDT is a Vietnamese dependency treebank, consisting of 10K+ sentences. We conducted experiments of Vietnamese dependency parsing on our VnDT Treebank consisting of 10200 trees (219k words). The VnDT Treebank is automatically converted from the input Vietnamese Treebank based on our new conversion approach. |
| Subsets | gold_standard, predicted |
| Languages | vie |
| Tasks | Dependency Parsing |
| License | Unknown (unknown) |
| Homepage | https://github.com/datquocnguyen/VnDT |
| HF URL | - |
| Paper URL | https://github.com/datquocnguyen/VnDT/blob/master/VnDT-paper-CameraReadyVersion.pdf |

**Comment by bp-high** [comment]
#self-assign

**Comment by bp-high** [comment]
Yep working on this issues got busy with some things but will try to wrap this issues by next week.

**Comment by sabilmakbar** [comment]
Thanks for letting us know, @bp-high, I'm removing the stale tag for now. Please add a tag `pr-ready` whenever you have finished on your dataloader so that the bot won't tag this issue as stale or let us know if you need more time for this issue.

**Comment by bp-high** [comment]
Sorry couldn't work on this last weekend due to christmas holidays and celebration will try to conclude this, this weekend.

**Comment by sabilmakbar** [comment]
Thanks for the update, @bp-high! no rush on this; please take your time to enjoy ur holiday!

**Comment by raileymontalan** [comment]
#self-assign

**Comment by raileymontalan** [comment]
Hi @holylovenia and @SamuelCahyawijaya, for this task, I plan to use the `load_ud_data_as_seacrowd_kb` function from `utils/common_parser.py`. Unfortunately, this function assumes that a CoNLL file provided must contain the `sent_id`, `text`, and other fields from a fully annotated CoNLL file. 

Unfortunately, the data from this VnDT dataset does not have these fields, as these fields are technically optional for CoNLL files. Therefore, using the function throws an error. How would you recommend to proceed with this? Thanks!

**Comment by raileymontalan** [comment]
Hi, I implemented a function to impute the missing `sent_id` and `text` fields. For `sent_id`, it just generates a unique id on the fly. For `text`, the function naively concatenates the tokens with spaces in between, regardless if the `.conll` file contains `SpaceAfter` field or otherwise. 

Please let me know if this is a valid approach. Thanks!
