### ISSUE TITLE
Create dataset loader for PhoATIS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#139]
Dataloader name: `phoatis/phoatis.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?phoatis

|     Dataset| phoatis |
|-------------|---|
| Description | This is first public intent detection and slot filling dataset for Vietnamese. The data contains 5871 English utterances from ATIS that are manually translated by professional translators into Vietnamese. |
| Subsets | - |
| Languages | vie |
| Tasks | Slot Filling, Intent Classification |
| License | Unknown (unknown) |
| Homepage | https://github.com/VinAIResearch/JointIDSF |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2104.02021 |

**Comment by dehanalkautsar** [comment]
#self-assign

**Comment by dehanalkautsar** [comment]
I’ll create all the dataloaders assigned to me this week

**Comment by dehanalkautsar** [comment]
Hi @holylovenia @SamuelCahyawijaya @sabilmakbar I want to ask something. For now, there is still no such thing as Slot Filling Task in the utils/constants.py. I wonder if it's okay if I add Tasks.SLOT_FILLING myself to the utils/constants.py file in the "Single Text Sequence Labeling" section? The feature output itself will follow utils/schemas/seq_label.py
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/68471412/5fd3cfc1-af99-4d56-926f-447c9f1883ac)

**Comment by dehanalkautsar** [comment]
And for this multiple tasks dataset case, what should I write in this line?
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/68471412/163584eb-8168-4930-877f-488e8716a832)

**Comment by holylovenia** [comment]
> Hi @holylovenia @SamuelCahyawijaya @sabilmakbar I want to ask something. For now, there is still no such thing as Slot Filling Task in the utils/constants.py. I wonder if it's okay if I add Tasks.SLOT_FILLING myself to the utils/constants.py file in the "Single Text Sequence Labeling" section? The feature output itself will follow utils/schemas/seq_label.py ![image](https://private-user-images.githubusercontent.com/68471412/292218141-5fd3cfc1-af99-4d56-926f-447c9f1883ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjI5NTcsIm5iZiI6MTcwMzU2MjY1NywicGF0aCI6Ii82ODQ3MTQxMi8yOTIyMTgxNDEtNWZkM2NmYzEtYWY5OS00ZDU2LTkyNmYtNDQ3YzlmMTg4M2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAzNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYzZhZDFkZjhiNTk4ODQwNjFjMTY0ODc1NWU1ZWUxOTQyNmUzYmUxOTRmMzE3ODg0NTE4MzY0MDA1MjFjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s5nlRQxGZAL3wMH18opTe54KpsQAUfYtWwNwO8JQ00U)

Sure, please make a separate PR for the new task and schema. Thank you, @dehanalkautsar!

**Comment by holylovenia** [comment]
> And for this multiple tasks dataset case, what should I write in this line? ![image](https://private-user-images.githubusercontent.com/68471412/292227169-163584eb-8168-4930-877f-488e8716a832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjI5NTcsIm5iZiI6MTcwMzU2MjY1NywicGF0aCI6Ii82ODQ3MTQxMi8yOTIyMjcxNjktMTYzNTg0ZWItODE2OC00OTMwLTg3N2YtNDg4ZTg3MTZhODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAzNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhM2YzODNkMGE5ODk1ZDI3ZWEzNDFlNGMyNDdhZjAyMGNhYjY1ZGQ5ODI3ZmUwMmIzZGNlZTg5OWRkOGFmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUVE1xioyjqlI2HU6XwsbPaXrOC1A1cAp2nGuUIWLY8)

You can use the subset name as well, e.g., `phoatis_slot_seacrowd_seq_label` and `phoatis_intent_seacrowd_text`.

**Comment by dehanalkautsar** [comment]
aah okay then, thanks!

**Comment by sabilmakbar** [comment]
Hi @dehanalkautsar, you can create a single datalaoder for multiple task, rather than separating it into 2. I think what Holy intended to say is to create a separate PR for changing the config, not splitting the dataset loader implementation into 2 different dataloaders.

**Comment by dehanalkautsar** [comment]
Oh, I thought what @holylovenia intended to say was to create 2 different dataloaders. Because I also saw some implemented dataloaders that divide a dataset according to its tasks. (e.g. https://github.com/SEACrowd/seacrowd-datahub/tree/master/seacrowd/sea_datasets/nusatranslation_mt & https://github.com/SEACrowd/seacrowd-datahub/tree/master/seacrowd/sea_datasets/nusatranslation_senti)

**Comment by sabilmakbar** [comment]
Hi @dehanalkautsar, apologies for tardy reply. You can check on here for existing implementation:
https://github.com/SEACrowd/seacrowd-datahub/tree/master/seacrowd/sea_datasets/code_mixed_jv_id
