### ISSUE TITLE
Create dataset loader for ara-close-lange

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#14]
Dataloader name: `ara_close/ara_close.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ara_close

|     Dataset| ara_close |
|-------------|---|
| Description | The dataset contribution of this study is a compilation of short fictional stories written in Bikol for readability assessment. The data was combined other collected Philippine language corpora, such as Tagalog and Cebuano.  The data from these languages are all distributed across the Philippine elementary system's first three grade levels (L1, L2, L3). We sourced this dataset from Let's Read Asia (LRA), Bloom Library, Department of Education, and Adarna House. |
| Subsets | - |
| Languages | bcl, tgl, ceb |
| Tasks | Readibility Assessment |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/imperialite/ara-close-lang |
| HF URL | - |
| Paper URL | https://aclanthology.org/2023.findings-acl.331/ |

**Comment by androstj** [comment]
#self-assign

**Comment by imperialite** [comment]
Hello. I'm the owner of this dataset and was about to submit it through the form provided, but it seems someone has already done it. Can I submit a new form? I'm sure I can fill up some of the details more clearly. Also, so I can be attributed for the points.

**Comment by androstj** [comment]
@imperialite Hi, I un-assign myself, you can take this task :)

**Comment by sabilmakbar** [comment]
Hi @imperialite do you want to take this dataloader task so you can get points from it?

**Comment by sabilmakbar** [comment]
Hi @androstj, since he isn't responding to your last comment on this Issue after 2 weeks, I think you may retake this issue again

**Comment by imperialite** [comment]
Hi @sabilmakbar thanks for this. I'll resubmit the data details to the form again. I'm contributing by adding more data than implementing data loaders. @androstj feel free to retake the issue again and sorry for the delay :)

**Comment by SamuelCahyawijaya** [comment]
@imperialite: Oh, I just realized that the previous one was about the datasheet. I will recheck the new submission and the score will be shared in this case.

**Comment by MJonibek** [comment]
#self-assign

**Comment by MJonibek** [comment]
Can you please advise, which schema I need to use for this dataset?

I was thinking about text schema (for text classification) with labels L1, L2 and L3, but I am not sure.

**Comment by imperialite** [comment]
Hi @MJonibek yes using the labels L1, L2, and L3 is correct and these are the same as what we used in the paper. Thanks.

**Comment by sabilmakbar** [comment]
for the schema in SEACrowd, you can use the text label schema (under `utils/schema/text.py`). However, since the `READABILITY_ASSESSMENT` task isn't available on the `_SUPPORTED_TASK` list yet, I'll help with adding that.

**Comment by MJonibek** [comment]
I found out that data for [tgl](https://github.com/imperialite/ara-close-lang/tree/main/data/tagalog) was deleted. 

Also, data has titles and text. For text label schema (utils/schema/text.py), 
{
                    "id": idx,
                    "text": text,
                    "label": label,
}

need I:

1.  append title to text
2. use title as id
3. just ignore title?

**Comment by imperialite** [comment]
I deleted the Tagalog (tgl) data because the owner (Adarna House) would prefer if it is requested directly through them. The title can be the ID since it can be used for checking duplication and additional info on the books (useful for genre-based or author analysis).
