### ISSUE TITLE
Create dataset loader for Dengue Filipino

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#140]
Dataloader name: `dengue_filipino/dengue_filipino.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?dengue_filipino

|     Dataset| dengue_filipino |
|-------------|---|
| Description | Benchmark dataset for low-resource multiclass classification, with 4,015 training, 500 testing, and 500 validation examples, each labeled as part of five classes. Each sample can be a part of multiple classes. Collected as tweets. |
| Subsets | - |
| Languages | fil, tgl |
| Tasks | Text Classification |
| License | Unknown (unknown) |
| Homepage | https://huggingface.co/datasets/dengue_filipino |
| HF URL | https://huggingface.co/datasets/dengue_filipino |
| Paper URL | https://ieeexplore.ieee.org/document/8459963 |

**Comment by williamnixon20** [comment]
#self-assign

**Comment by ilhamfp** [comment]
#self-assign
