### ISSUE TITLE
Create dataset loader for Abui WordNet

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#143]
Dataloader name: `abui_wordnet/abui_wordnet.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?abui_wordnet

|     Dataset| abui_wordnet |
|-------------|---|
| Description | A small fully hand-checked wordnet for Abui, containing over 1,400 concepts and 3,600 senses, is created. A bootstrapping technique is introduced to utilise the information in the gloss fields (English, national, and regional) to generate sense candidates using a naive algorithm based on multilingual sense intersection. |
| Subsets | - |
| Languages | abz |
| Tasks | Wordnet |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/fanacek/abuiwn |
| HF URL | - |
| Paper URL | https://aclanthology.org/2022.fieldmatters-1.7/ |

**Comment by muhsatrio** [comment]
#self-assign

**Comment by Gyyz** [comment]
#self-assign
