### ISSUE TITLE
Create dataset loader for Thai Depression Dataset

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#145]
Dataloader name: `thai_depression/thai_depression.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_depression

|     Dataset| thai_depression |
|-------------|---|
| Description | The corpus is a compilation of 944 expert-verified cases of depression in several online blogs (Storylog, bloggang, and lblogspot) written in Thai. The blog posts are further split into sentences in the data to fine-tune Thai BERT models. |
| Subsets | - |
| Languages | tha |
| Tasks | Text Classification |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://zenodo.org/records/4734552 |
| HF URL | - |
| Paper URL | https://aclanthology.org/2021.wnut-1.3/ |

**Comment by williamnixon20** [comment]
#self-assign

**Comment by muhsatrio** [comment]
#self-assign

**Comment by ilhamfp** [comment]
#self-assign

**Comment by ilhamfp** [comment]
still working on it :)

**Comment by holylovenia** [comment]
@ilhamfp Thanks for letting us know!! Just let us know if you need any help. 🙏
