### ISSUE TITLE
Create dataset loader for Multilingual Spoken Words Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#146]
Dataloader name: `mswc/mswc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mswc

|     Dataset| mswc |
|-------------|---|
| Description | Multilingual Spoken Words Corpus is a large and growing audio dataset of spoken words in 50 languages collectively spoken by over 5 billion people, for academic research and commercial applications in keyword spotting and spoken term search, licensed under CC-BY 4.0. The dataset contains over 340,000 keywords, totaling 23.4 million 1-second spoken examples (over 6,000 hours). Three of the SEA languages are present in this dataset; namely Hakha Chin, Indonesian, and Vietnamese. |
| Subsets | cnh_wav, ind_wav, vie_wav, cnh_opus, ind_opus, vie_opus |
| Languages | cnh, ind, vie |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://huggingface.co/datasets/MLCommons/ml_spoken_words |
| HF URL | https://huggingface.co/datasets/MLCommons/ml_spoken_words |
| Paper URL | https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/file/fe131d7f5a6b38b23cc967316c13dae2-Paper-round2.pdf |

**Comment by akhdanfadh** [comment]
I'll work on all my assigned dataloaders this weekend.

**Comment by sabilmakbar** [comment]
Hi @akhdanfadh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by Enliven26** [comment]
#self-assign
