### ISSUE TITLE
Create dataset loader for GATITOS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#147]
Dataloader name: `gatitos/gatitos.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?gatitos

|     Dataset| gatitos |
|-------------|---|
| Description | The GATITOS (Google's Additional Translations Into Tail-languages: Often Short) dataset is a high-quality, multi-way parallel dataset of tokens and short phrases. This dataset consists in 4,000 English segments (4,500 tokens) that have been translated into each of 173 languages, 170 of which are low-resource, 23 are spoken in Southeast Asia. This dataset contains primarily short segments: 93% single tokens, and only 23 sentences (0.6%) have over 5 tokens. As such it is best thought of as a multilingual lexicon, rather than a parallel training corpus. The source text is frequent words in the English Language, along with some common phrases and short sentences. Care has been taken to ensure that they include good coverage of numbers, months, days of the week, swadesh words, and names of the languages themselves (including the endonym). |
| Subsets | ace, ban, bbc, bew, bjn, bts, btx, bug, cnh, hil, iba, ilo, kac, lus, mad, mak, meo, min, pag, pam, shn, tet, war |
| Languages | ace, ban, bbc, bew, bjn, bts, btx, bug, cnh, hil, iba, ilo, kac, lus, mad, mak, meo, min, pag, pam, shn, tet, war |
| Tasks | Machine Translation |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/google-research/url-nlp/blob/main/gatitos/README.md |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2303.15265 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
I'll work on all my assigned dataloaders this weekend.

**Comment by holylovenia** [comment]
Okay then, @akhdanfadh. Feel free to let us know if you need any help!

**Comment by sabilmakbar** [comment]
Hi @akhdanfadh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by bryanwilie** [comment]
#self-assign

**Comment by bryanwilie** [comment]
Still trying to do something this weekend. Will notify further later!

**Comment by bryanwilie** [comment]
I don't think I could work on this eventually, sorry, I think I'll unassign myself for now.

**Comment by ssun32** [comment]
#self-assign
