### ISSUE TITLE
Create dataset loader for Filipino Slang Spelling Normalization

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#15]
Dataloader name: `filipino_slang_norm/filipino_slang_norm.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?filipino_slang_norm

|     Dataset| filipino_slang_norm |
|-------------|---|
| Description | This dataset contains 398 abbreviated and/or contracted Filipino words used in Facebook comments made on weather advisories from a Philippine weather bureau. Each word contains three "correct" versions provided by three undergraduate volunteers. |
| Subsets | - |
| Languages | fil |
| License | Unknown (unknown) |
| Homepage | https://github.com/ljyflores/efficient-spelling-normalization-filipino |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2210.02675 |

**Comment by ljvmiranda921** [comment]
Also interested in this!

**Comment by ljvmiranda921** [comment]
#self-assign
