### ISSUE TITLE
Create dataset loader for Bloom-vist

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#158]
Dataloader name: `bloom_vist/bloom_vist.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?bloom_vist

|     Dataset| bloom_vist |
|-------------|---|
| Description | BLOOM VIST is a visual storytelling of books that consists of 62 languages indigenous to SEA. This dataset is owned by Bloom, a free, open-source software developed by SIL International and associated with Bloom Library, app, and services. This dataset is released with the LICENSE family of Creative Commons (although each story datapoints has its licensing in more detail, e.g cc-by, cc-by-nc, cc-by-nd, cc-by-sa, cc-by-nc-nd, cc-by-nc-sa) |
| Subsets | abc, ahk, bfn, bjn, bkx, brb, brv, bya, bzi, ceb, cgc, cmo, ddg, dmg, dnw, dtp, enc, fil, hil, hro, idt, ilo, ind, jra, kak, khb, khm, kqr, krr, ksw, lhu, lsi, lwl, mdr, mgm, mhx, mkz, mry, msb, mya, nod, nxa, nxl, pag, pce, pea, pmf, psp, sea, sgd, sml, snl, tdt, tet, tha, tkd, tpu, war, wms, yet, yin, zlm |
| Languages | abc, ahk, bfn, bjn, bkx, brb, brv, bya, bzi, ceb, cgc, cmo, ddg, dmg, dnw, dtp, enc, fil, hil, hro, idt, ilo, ind, jra, kak, khb, khm, kqr, krr, ksw, lhu, lsi, lwl, mdr, mgm, mhx, mkz, mnw, mqj, mry, msb, mya, nod, nxa, nxl, pag, pce, pea, pmf, psp, sea, sgd, sml, snl, tdt, tet, tha, tkd, tpu, war, wms, yet, yin, zlm |
| Tasks | Visual Storytelling |
| License | Creative Commons license family (cc) |
| Homepage | https://huggingface.co/datasets/sil-ai/bloom-vist |
| HF URL | https://huggingface.co/datasets/sil-ai/bloom-vist |
| Paper URL | https://aclanthology.org/2022.emnlp-main.590 |

**Comment by sabilmakbar** [comment]
#self-assign
