### ISSUE TITLE
Create dataset loader for CC-Aligned

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#159]
Dataloader name: `cc_aligned_doc/cc_aligned_doc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?cc_aligned_doc

|     Dataset| cc_aligned_doc |
|-------------|---|
| Description | CCAligned consists of parallel or comparable web-document pairs in 137 languages aligned with English (10 languages are from Southeast Asia; Burmese has two document collection with different scripts). These web-document pairs were constructed by performing language identification on raw web-documents, and ensuring corresponding language codes were corresponding in the URLs of web documents. This pattern matching approach yielded more than 100 million aligned documents paired with English. |
| Subsets | id_ID, su_ID, th_TH, vi_VN, ms_MY, lo_LA, km_KH, my_MM, my_MM_zaw, cx_PH, wy_PH |
| Languages | ind, sun, tha, vie, zlm, lao, khm, mya, ceb, war |
| Tasks | Machine Translation |
| License | Unknown (unknown) |
| Homepage | https://www2.statmt.org/cc-aligned/ |
| HF URL | https://huggingface.co/datasets/ccaligned_multilingual |
| Paper URL | https://aclanthology.org/2020.emnlp-main.480 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by holylovenia** [comment]
Hi @akhdanfadh, we are freeing up this dataloader issue due to the lack of response so other contributors can `#self-assign`.

**Comment by MJonibek** [comment]
#self-assign
