### ISSUE TITLE
Create dataset loader for ICON

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#161]
Dataloader name: `icon/icon.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?icon

|     Dataset| icon |
|-------------|---|
| Description | ICON (Indonesian CONstituency treebank) is a large-scale high-quality constituency treebank (10000 sentences) for the Indonesian language, sourced from Wikipedia and news data from Tempo, spanning the period from 1971 to 2016. The annotation guidelines were formulated with the Penn Treebank POS tagging and bracketing guidelines as a reference, with additional adaptations to account for the characteristics of the Indonesian language. |
| Subsets | - |
| Languages | ind |
| Tasks | Constituency Parsing |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/aisingapore/seacorenlp-data/tree/main/id/constituency |
| HF URL | - |
| Paper URL | https://aclanthology.org/2023.tlt-1.5/ |

**Comment by Gyyz** [comment]
Finished, will upload later

**Comment by holylovenia** [comment]
@Gyyz Sure, thanks in advance! Happy holidays 🎄

**Comment by Gyyz** [comment]
#254 pull request
