### ISSUE TITLE
Create dataset loader for Bloom-captioning

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#162]
Dataloader name: `bloom_captioning/bloom_captioning.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?bloom_captioning

|     Dataset| bloom_captioning |
|-------------|---|
| Description | This is a Bloom Library dataset developed for the image captioning task. It covers 74 languages indigenous to SEA overall, amounting to total data of 21K. This dataset belongs to a CC license, where its datapoints has specific license attached to it |
| Subsets | abc, ahk, bfn, bjn, bkx, brb, brv, bya, bzi, ceb, cgc, cmo, ddg, dmg, dnw, dtp, dtr, enc, fil, gal, hil, hre, hro, idt, ilo, ind, jra, kak, khb, khm, kqr, krr, ksw, lhu, llg, lsi, lwl, mdr, mgm, mhx, mkz, mnw, mqj, mry, msb, mya, nod, nst, nxa, nxl, pag, pce, pdu, pea, pmf, sea, sgd, shn, sml, snl, tdt, tet, tha, tkd, tnt, tom, tpu, vie, war, wms, wnk, xmm, yet, zlm |
| Languages | abc, ahk, bfn, bjn, bkx, brb, brv, bya, bzi, ceb, cgc, cmo, ddg, dmg, dnw, dtp, dtr, enc, fil, gal, hil, hre, hro, idt, ilo, ind, jra, kak, khb, khm, kqr, krr, ksw, lhu, llg, lsi, lwl, mdr, mgm, mhx, mkz, mnw, mqj, mry, msb, mya, nod, nst, nxa, nxl, pag, pce, pdu, pea, pmf, sea, sgd, shn, sml, snl, tdt, tet, tha, tkd, tnt, tom, tpu, vie, war, wms, wnk, xmm, yet, zlm |
| Tasks | Image-to-Text Generation |
| License | Creative Commons license family (cc) |
| Homepage | https://huggingface.co/datasets/sil-ai/bloom-captioning |
| HF URL | https://huggingface.co/datasets/sil-ai/bloom-captioning |
| Paper URL | https://aclanthology.org/2022.emnlp-main.590 |

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Have drafted the PR, removing the `staled-issue` label
