### ISSUE TITLE
Create dataset loader for Bloom-speech

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#163]
Dataloader name: `bloom_speech/bloom_speech.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?bloom_speech

|     Dataset| bloom_speech |
|-------------|---|
| Description | This version of the Bloom Library data is developed specifically for the automatic speech recognition and speech-to-text tasks. It includes data from 56 languages across 18 language families. 8 languages are spoken in Southeast Asia |
| Subsets | bjn, bzi, ceb, ind, jra, kqr, mya, tgl |
| Languages | bjn, bzi, ceb, ind, jra, kqr, mya, tgl |
| Tasks | Speech-to-Text Translation, Text-To-Speech Synthesis |
| License | Other (other) |
| Homepage | https://huggingface.co/datasets/sil-ai/bloom-speech |
| HF URL | https://huggingface.co/datasets/sil-ai/bloom-speech |
| Paper URL | https://aclanthology.org/2022.emnlp-main.590 |

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Will draft a PR later today.
