### ISSUE TITLE
Create dataset loader for OpenSLR

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#164]
Dataloader name: `openslr/openslr.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?openslr

|     Dataset| openslr |
|-------------|---|
| Description | This data set contains transcribed high-quality audio of Javanese, Sundanese, Burmese, Khmer. This data set come from 3 different projects under OpenSLR initiative |
| Subsets | SLR35 (javanese), SLR36 (sundanese), SLR41 (javanese), SLR42 (khmer), SLR44 (sundanese), SLR80 (burmese) |
| Languages | mya, jav, sun, khm |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://www.openslr.org/resources.php |
| HF URL | https://huggingface.co/datasets/openslr |
| Paper URL | http://dx.doi.org/10.21437/SLTU.2018-11 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by holylovenia** [comment]
Hi @akhdanfadh, we are freeing up this dataloader issue due to the lack of response so other contributors can #self-assign.

**Comment by MJonibek** [comment]
#self-assign

**Comment by MJonibek** [comment]
#self-assign
