### ISSUE TITLE
Create dataset loader for Bloom-LM

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#165]
Dataloader name: `bloom_lm/bloom_lm.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?bloom_lm

|     Dataset| bloom_lm |
|-------------|---|
| Description | This version of the Bloom Library data is developed specifically for the language modeling task. It includes data from 364 languages across 31 language families. 33 languages are spoken in Southeast Asia. |
| Subsets | ahk, bfn, bkx, brb, bzi, ceb, cgc, cmo, ddg, dtp, fil, gal, idt, ind, jra, kak, khb, khm, krr, lhu, lsi, mgm, mhx, mkz, mya, nxa, pce, tdt, tet, tha, tpu, war, zlm |
| Languages | ahk, bfn, bkx, brb, bzi, ceb, cgc, cmo, ddg, dtp, fil, gal, idt, ind, jra, kak, khb, khm, krr, lhu, lsi, mgm, mhx, mkz, mya, nxa, pce, tdt, tet, tha, tpu, war, zlm |
| Tasks | Language Modeling |
| License | Other (other) |
| Homepage | https://huggingface.co/datasets/sil-ai/bloom-lm |
| HF URL | https://huggingface.co/datasets/sil-ai/bloom-lm |
| Paper URL | https://aclanthology.org/2022.emnlp-main.590 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by holylovenia** [comment]
Hi @akhdanfadh, we are freeing up this dataloader issue due to the lack of response so other contributors can `#self-assign`.

**Comment by sabilmakbar** [comment]
#self-assign
