### ISSUE TITLE
Create dataset loader for Audio Keyword Spotting

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#166]
Dataloader name: `audio_keyword_spotting/audio_keyword_spotting.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?audio_keyword_spotting

|     Dataset| audio_keyword_spotting |
|-------------|---|
| Description | This dataset is a ASR for short text & voices, focusing in identifying common words (or keywords) with entities of Person name and Place Name found in Bible, as found in trabina (https://github.com/wswu/trabina). |
| Subsets | ind |
| Languages | ind |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://huggingface.co/datasets/sil-ai/audio-keyword-spotting |
| HF URL | https://huggingface.co/datasets/sil-ai/audio-keyword-spotting |
| Paper URL | https://huggingface.co/datasets/sil-ai/audio-keyword-spotting |

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Will work on this, shd be done by tmrw
