### ISSUE TITLE
Create dataset loader for Philippine Fake News Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#17]
Dataloader name: `ph_fake_news_corpus/ph_fake_news_corpus.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ph_fake_news_corpus

|     Dataset| ph_fake_news_corpus |
|-------------|---|
| Description | The Philippine Fake News Corpus consists of news headlines and content from various "credible" and "non-credible" national news outlets. "Credible" sources were national broadsheets available in the National Library of the Philippines, while "non-credible" sources were sources included in lists of websites with fake or unverified content provided by government and private institutions. |
| Subsets | - |
| Languages | eng |
| Tasks | Fact Checking |
| License | Unknown (unknown) |
| Homepage | https://github.com/aaroncarlfernandez/Philippine-Fake-News-Corpus |
| HF URL | - |
| Paper URL | https://dl.acm.org/doi/abs/10.1145/3326467.3326490 |

**Comment by kgtgeo** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
There is yet schema for `Tasks.FACT_CHECKING`, but I think it could be `text`, right? Since we just want to classify whether the news is credible or not.

**Comment by sabilmakbar** [comment]
The scope of `Tasks.FACT_CHECKING` isn't generalizable well. Therefore, there's no applicable SEACrowd Schema for now; you just need to load as is (for `source` schema).

**Comment by sabilmakbar** [comment]
Hi @kgtgeo, may I know the current status of this dataloader creation? Feel free to discuss here if you have any difficulties. Thanks!

**Comment by holylovenia** [comment]
Hi @kgtgeo, we received no response from you regarding this dataloader, so I will remove your assignment.

Anyone interested in taking this dataloader, please feel free to `#self-assign`.

**Comment by nabilazahra** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @nabilazahra, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by elyanah-aco** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
nvm this has PR attached already
