### ISSUE TITLE
Create new task and schema for dialogue system datasets

### ISSUE THREAD

**Issue by holylovenia** [SEACrowd/seacrowd-datahub#172]
Relates #53 and [an existing dataloader (i.e., COD)](https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/sea_datasets/cod/cod.py).

Question for thought: Since Wizard-of-Oz (WOZ) format is quite popular for task-oriented dialogue systems, should we make our schema similar to it? (cc: @SamuelCahyawijaya @sabilmakbar)

**Comment by sabilmakbar** [comment]
hi @holylovenia, are CoD & xPersona dataloaders included in this revamp, too?

**Comment by sabilmakbar** [comment]
I think there are a few more dataloaders that will use this schema:
1. Issue #83 
2. Issue #54 

Therefore, shall we make this a high-priority task?

**Comment by sabilmakbar** [comment]
btw @holylovenia, do you happen to know the dataset link (or at least its schema explanation) for this original [WoZ paper](https://aclanthology.org/E17-1042/)?

I also read a few other relevant articles/papers worth a look:
1. [WoZ Framework](https://en.wikipedia.org/wiki/Wizard_of_Oz_experiment) (This is the Wiki Article of WoZ Framework to what the WoZ paper mentions -- from the same inventor, Kelley)
2. [MultiWoZ](https://aclanthology.org/D18-1547/)
3. [Evaluation using MultiWoZ](https://aclanthology.org/P19-1078/)

**Comment by holylovenia** [comment]
Hi @sabilmakbar, sorry for the late reply. Yes, let's make it a high priority. As far as I know, the original dataset should be [this](https://huggingface.co/datasets/woz_dialogue).

**Comment by dehanalkautsar** [comment]
Hi @holylovenia @sabilmakbar @SamuelCahyawijaya . I've implemented the schema based on the link above (https://huggingface.co/datasets/woz_dialogue). The PR is in here #237  , let me know as soon as possible if there are some mistakes or not because I need this schema to implement #53 , #54 , and #83 . Thanks!
