### ISSUE TITLE
Create dataset loader for indo_story_cloze

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#179]
Dataloader name: `indo_story_cloze/indo_story_cloze.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indo_story_cloze

|     Dataset| indo_story_cloze |
|-------------|---|
| Description | This is the first commonsense reasoning dataset in Indonesian. IndoStoryCloze is a story in our dataset that consists of the four-sentence premise, one-sentence correct ending, and one-sentence incorrect ending. In total, we have created 2,325 Indonesian stories with the train/dev/test split 1,000/200/1,135. |
| Subsets | - |
| Languages | ind |
| Tasks | Commonsense Reasoning |
| License | MIT (mit) |
| Homepage | https://huggingface.co/datasets/indolem/indo_story_cloze |
| HF URL | https://huggingface.co/datasets/indolem/indo_story_cloze |
| Paper URL | https://aclanthology.org/2022.csrr-1.2.pdf |

**Comment by chenxwh** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @chenxwh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by chenxwh** [comment]
Hi @sabilmakbar,

It is implemented and the PR is here: https://github.com/SEACrowd/seacrowd-datahub/pull/323

**Comment by sabilmakbar** [comment]
Thanks @chenxwh, didn't see that.

For coming PR, mind addisng this in the initial PR message:
`Closes #179`

so that it will be linked to this issue and checking process will be easier
