### ISSUE TITLE
Create dataset loader for IndoMMLU

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#180]
Dataloader name: `indommlu/indommlu.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indommlu

|     Dataset| indommlu |
|-------------|---|
| Description | IndoMMLU is the first multi-task language understanding benchmark for Indonesian culture and languages, which consists of questions from primary school to university entrance exams in Indonesia. By employing professional teachers, we obtained 14,906 questions across 63 tasks and education levels, with 46% of the questions focusing on assessing proficiency in the Indonesian language and knowledge of nine local languages and cultures in Indonesia. |
| Subsets | - |
| Languages | ind |
| Tasks | Question Answering |
| License | Creative Commons Attribution 2.0 (cc-by-2.0) |
| Homepage | https://huggingface.co/datasets/indolem/IndoMMLU |
| HF URL | https://huggingface.co/datasets/indolem/IndoMMLU |
| Paper URL | https://arxiv.org/pdf/2310.04928.pdf |

**Comment by chenxwh** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @chenxwh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by chenxwh** [comment]
Hi @sabilmakbar,

It is implemented and the PR is here: https://github.com/SEACrowd/seacrowd-datahub/pull/324

**Comment by sabilmakbar** [comment]
Thanks @chenxwh, didn't see that.

For coming PR, mind addisng this in the initial PR message:
`Closes #180`

so that it will be linked to this issue and checking process will be easier
