### ISSUE TITLE
Create dataset loader for Thai-Sum

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#181]
Dataloader name: `thai_sum/thai_sum.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_sum

|     Dataset| thai_sum |
|-------------|---|
| Description | We present ThaiSum, a large-scale corpus for Thai text summarization obtained from several online news websites namely Thairath, ThaiPBS, Prachathai, and The Standard. This dataset consists of over 350,000 article and summary pairs written by journalists. |
| Subsets | - |
| Languages | tha |
| Tasks | Summarization |
| License | MIT (mit) |
| Homepage | https://github.com/nakhunchumpolsathien/ThaiSum |
| HF URL | https://huggingface.co/datasets/thaisum |
| Paper URL | https://www.researchgate.net/publication/367166731_Using_Knowledge_Distillation_from_Keyword_Extraction_to_Improve_the_Informativeness_of_Neural_Cross-lingual_Summarization |

**Comment by jen-santoso** [comment]
#self-assign

**Comment by jen-santoso** [comment]
#self-assign
