### ISSUE TITLE
Create dataset loader for ROOTS_vi_ted

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#182]
Dataloader name: `roots_vi_ted/roots_vi_ted.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?roots_vi_ted

|     Dataset| roots_vi_ted |
|-------------|---|
| Description | ROOTS_vi_ted is a subset of Vietnamese in ted_talks_iwslt datasets. ted_talks_iwslt is a collection of the original Ted talks and their translated version. The translations are available in more than 109+ languages, though the distribution is not uniform. |
| Subsets | - |
| Languages | vie |
| Tasks | Language Modeling |
| License | Creative Commons Attribution Non Commercial 2.0 (cc-by-nc-2.0) |
| Homepage | https://huggingface.co/datasets/bigscience-data/roots_vi_ted_talks_iwslt |
| HF URL | https://huggingface.co/datasets/bigscience-data/roots_vi_ted_talks_iwslt |
| Paper URL | https://arxiv.org/abs/2303.03915 |

**Comment by chenxwh** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @chenxwh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by chenxwh** [comment]
Hi @sabilmakbar, 

I am working on this and will submit a PR by the end of Monday.
