### ISSUE TITLE
Create dataset loader for Wongnai Reviews

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#183]
Dataloader name: `wongnai_reviews/wongnai_reviews.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?wongnai_reviews

|     Dataset| wongnai_reviews |
|-------------|---|
| Description | Wongnai features over 200,000 restaurants, beauty salons, and spas across Thailand on its platform, with detailed information about each merchant and user reviews. Its over two million registered users can search for what’s top rated in Bangkok, follow their friends, upload photos, and do quick write-ups about the places they visit.  Each write-up(review) also comes with a rating score ranging from 1-5 stars. The task here is to create a rating prediction model using only textual information. |
| Subsets | - |
| Languages | tha |
| Tasks | Text Classification |
| License | GNU Lesser General Public License v3.0 (lgpl-3.0) |
| Homepage | https://github.com/wongnai/wongnai-corpus |
| HF URL | https://huggingface.co/datasets/wongnai_reviews |
| Paper URL | https://github.com/wongnai/wongnai-corpus |

**Comment by chenxwh** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @chenxwh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by chenxwh** [comment]
Hi @sabilmakbar,

It is implemented and the PR is here: https://github.com/SEACrowd/seacrowd-datahub/pull/325

**Comment by sabilmakbar** [comment]
Thanks @chenxwh, didn't see that.

For coming PR, mind addisng this in the initial PR message:
`Closes #183`

so that it will be linked to this issue and checking process will be easier
