### ISSUE TITLE
Create dataset loader for STB_EXT

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#187]
Dataloader name: `stb_ext/stb_ext.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?stb_ext

|     Dataset| stb_ext |
|-------------|---|
| Description | We adopt the Universal Dependencies protocol for constructing the Singlish dependency treebank, both as a new resource for the low-resource languages and to facilitate knowledge transfer from English. Briefly, the STB-EXT dataset offers a 3-times larger training set, while keeping the same dev and test sets from STB-ACL. We provide treebanks with both gold-standard as well as automatically generated POS tags. |
| Subsets | auto_pos_stack, auto_pos_multiview, en_ud_autopos, gold_pos |
| Languages | eng |
| Tasks | Dependency Parsing, POS Tagging |
| License | MIT (mit) |
| Homepage | https://github.com/wanghm92/Sing_Par/tree/master |
| HF URL | - |
| Paper URL | https://dl.acm.org/doi/10.1145/3321128 |

**Comment by Gyyz** [comment]
#self-assign

**Comment by Gyyz** [comment]
#256 pull request
