### ISSUE TITLE
Create dataset loader for Sea-bench

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#188]
Dataloader name: `seabench/seabench.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?seabench

|     Dataset| seabench |
|-------------|---|
| Description | Sea-bench is a multilingual benchmark for assistant-style models annotated by native linguists covering 8 Southeast Asian languages. The linguists sourced such data by manually translating open-source English test sets, collecting real user questions from local forums and websites, collecting real math and reasoning questions from reputable sources, as well as writing test instructions and questions themselves. The Sea-bench test set contains 20 questions per task (5 tasks for 3 languages, 4 tasks for other 5 languages). |
| Subsets | vi (Task-solving, Math-reasoning, General-instruction, NaturalQA, Safety), id (Task-solving, Math-reasoning, General-instruction, NaturalQA, Safety), th (Task-solving, Math-reasoning, General-instruction, NaturalQA, Safety), km (Task-solving, Math-reasoning, General-instruction, NaturalQA), lo (Task-solving, Math-reasoning, General-instruction, NaturalQA), ms (Task-solving, Math-reasoning, General-instruction, NaturalQA), my (Task-solving, Math-reasoning, General-instruction, NaturalQA), tl (Task-solving, Math-reasoning, General-instruction, NaturalQA) |
| Languages | tgl, khm, vie, tha, lao, mya, ind, zlm |
| Tasks | Instruction Tuning |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://huggingface.co/datasets/SeaLLMs/Sea-bench/raw/main/question.jsonl |
| HF URL | https://huggingface.co/datasets/SeaLLMs/Sea-bench |
| Paper URL | https://arxiv.org/pdf/2312.00738.pdf |

**Comment by MJonibek** [comment]
#self-assign

**Comment by raileymontalan** [comment]
#self-assign

**Comment by raileymontalan** [comment]
#self-assign

**Comment by holylovenia** [comment]
Hi @raileymontalan, are you still working on this issue?
