### ISSUE TITLE
Create dataset loader for TydiQA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#190]
Dataloader name: `tydiqa/tydiqa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tydiqa

|     Dataset| tydiqa |
|-------------|---|
| Description | TyDi QA is a question answering dataset covering 11 typologically diverse languages with 204K question-answer pairs. The languages of TyDi QA are diverse with regard to their typology -- the set of linguistic features that each language expresses -- such that we expect models performing well on this set to generalize across a large number of the languages in the world. It contains language phenomena that would not be found in English-only corpora. To provide a realistic information-seeking task and avoid priming effects, questions are written by people who want to know the answer, but don’t know the answer yet, (unlike SQuAD and its descendents) and the data is collected directly in each language without the use of translation (unlike MLQA and XQuAD). |
| Subsets | primary_task_indonesian, primary_task_thai, secondary_task_indonesian, secondary_task_thai |
| Languages | ind, tha |
| Tasks | Question Answering |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/google-research-datasets/tydiqa |
| HF URL | https://huggingface.co/datasets/tydiqa |
| Paper URL | https://aclanthology.org/2020.tacl-1.30/ |

**Comment by sabilmakbar** [comment]
Hi @SamuelCahyawijaya, we have `tydiqa_id`, which was carried over from NusaCrowd. Would it be better to unify the implementation?

**Comment by Gyyz** [comment]
#self-assign

**Comment by Gyyz** [comment]
For the secondary task, Thai is removed since the lack of whitespace breaks some tools. We can find the information at HF URL.

**Comment by Gyyz** [comment]
#251
