### ISSUE TITLE
Create dataset loader for iapp_wiki_qa_squad

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#191]
Dataloader name: `iapp_squad/iapp_squad.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?iapp_squad

|     Dataset| iapp_squad |
|-------------|---|
| Description | iapp_wiki_qa_squad, Open Thai Wikipedia QA is an extractive question answering dataset from Thai Wikipedia articles. It is adapted from the original iapp-wiki-qa-dataset to SQuAD format, resulting in 5761/742/739 questions from 1529/191/192 articles. |
| Subsets | - |
| Languages | tha |
| Tasks | Question Answering |
| License | MIT (mit) |
| Homepage | https://github.com/iapp-technology/iapp-wiki-qa-dataset |
| HF URL | https://huggingface.co/datasets/iapp_wiki_qa_squad |
| Paper URL | https://zenodo.org/records/4539916 |

**Comment by Gyyz** [comment]
#self-assign

**Comment by Gyyz** [comment]
#255 pull request
