### ISSUE TITLE
Create dataset loader for MALINDO_parallel

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#192]
Dataloader name: `malindo_parallel/malindo_parallel.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?malindo_parallel

|     Dataset| malindo_parallel |
|-------------|---|
| Description | Teks ini adalah skrip video untuk Kampus Terbuka Universiti Bahasa Asing Tokyo pada tahun 2020. Tersedia parallel sentences dalam Bahasa Melayu/Indonesia dan Bahasa Jepang |
| Subsets | - |
| Languages | zlm, ind |
| Tasks | Machine Translation |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/matbahasa/MALINDO_Parallel/tree/master/OpenCampusTUFS |
| HF URL | - |
| Paper URL | https://github.com/matbahasa/MALINDO_Parallel/blob/master/README.md |

**Comment by MJonibek** [comment]
#self-assign

**Comment by MJonibek** [comment]
Can you please help, for this dataset in their github repository there are two files:

OCTUFS2020-norm.txt
OCTUFS2020.txt

Both has parallel text, where one column is Japanese, and second one is Malay. But there is no Indonesian (but we have it in description and languages).

Do I need write dataloader for Maly-Japanese translation? If yes, which file to use?

**Comment by MJonibek** [comment]
Can you please help, for this dataset in their github repository there are two files:

OCTUFS2020-norm.txt
OCTUFS2020.txt

Both has parallel text, where one column is Japanese, and second one is Malay (as far as I understand). But there is no Indonesian (but we have it in description and languages).

Do I need write dataloader for Malay-Japanese translation? If yes, which file to use?

**Comment by bryanwilie** [comment]
#self-assign

**Comment by bryanwilie** [comment]
Already made a PR on this one 👍🏻

**Comment by sabilmakbar** [comment]
somehow the Issue and the PR isn't connected yet, thanks for the update, @bryanwilie!
