### ISSUE TITLE
Create dataset loader for MALINDO_Morph

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#193]
Dataloader name: `malindo_morph/malindo_morph.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?malindo_morph

|     Dataset| malindo_morph |
|-------------|---|
| Description | MALINDO Morph merupakan kamus morfologi untuk bahasa Melayu dan bahasa Indonesia. Kamus MALINDO Morph dilesenkan dengan pelesenan Creative Commons Attribution 4.0 International (CC BY 4.0). Untuk maklumat terperinci mengenai MALINDO Morph, sila rujuk makalah di bawah ini. |
| Subsets | Kamus Dewan, Kamus Besar Bahasa Indonesia, Leipzig Corpora Collection, Frogstory-David, Melayu-Standard-Lisan, Melayu-Sabah, Melayu-Sarawak, Melayu-Brunei, Indo-Jakarta-Lisan |
| Languages | zlm, ind |
| Tasks | Morphological Inflections |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/matbahasa/MALINDO_Morph |
| HF URL | - |
| Paper URL | http://lrec-conf.org/workshops/lrec2018/W29/pdf/8_W29.pdf |

**Comment by MJonibek** [comment]
#self-assign

**Comment by danjohnvelasco** [comment]
#self-assign
