### ISSUE TITLE
Create dataset loader for WIT

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#202]
Dataloader name: `wit/wit.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?wit

|     Dataset| wit |
|-------------|---|
| Description | Wikipedia-based Image Text (WIT) Dataset is a large multimodal multilingual dataset. WIT is composed of a curated set of 37.6 million entity rich image-text examples with 11.5 million unique images across 108 Wikipedia languages. 9 languages are spoken in Southeast Asia region |
| Subsets | - |
| Languages | ceb, fil, ind, jav, zlm, mya, tha, vie, war |
| Tasks | Image-to-Text Generation, Text-to-Image Generation |
| License | Creative Commons Attribution Share Alike 3.0 (cc-by-sa-3.0) |
| Homepage | https://github.com/google-research-datasets/wit/blob/main/DATA.md |
| HF URL | https://huggingface.co/datasets/google/wit |
| Paper URL | https://dl.acm.org/doi/abs/10.1145/3404835.3463257 |

**Comment by Alex-HaochenLi** [comment]
#self-assign

**Comment by khelli07** [comment]
#self-assign

**Comment by raileymontalan** [comment]
#self-assign

**Comment by raileymontalan** [comment]
#self-assign

**Comment by raileymontalan** [comment]
Unnecessary commits have been removed, PR ready.
