### ISSUE TITLE
Create dataset loader for Melayu_Standard_Lisan

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#203]
Dataloader name: `melayu_standard_lisan/melayu_standard_lisan.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?melayu_standard_lisan

|     Dataset| melayu_standard_lisan |
|-------------|---|
| Description | Korpus Variasi Bahasa Melayu: Standard Lisan is a language corpus sourced from monologues of various melayu folklores. |
| Subsets | - |
| Languages | zlm |
| Tasks | Language Modeling |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/matbahasa/Melayu_Standard_Lisan |
| HF URL | - |
| Paper URL | - |

**Comment by Alex-HaochenLi** [comment]
#self-assign

**Comment by Alex-HaochenLi** [comment]
Have submitted a PR. Please have a check.
