### ISSUE TITLE
Create dataset loader for Melayu_Sarawak

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#205]
Dataloader name: `melayu_sarawak/melayu_sarawak.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?melayu_sarawak

|     Dataset| melayu_sarawak |
|-------------|---|
| Description | Korpus Variasi Bahasa Melayu: Sarawak is a language corpus sourced from various folklores in Melayu Sarawak dialect. |
| Subsets | - |
| Languages | zlm |
| Tasks | Language Modeling |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/matbahasa/Melayu_Sarawak |
| HF URL | - |
| Paper URL | - |

**Comment by Alex-HaochenLi** [comment]
#self-assign

**Comment by Alex-HaochenLi** [comment]
Have submitted a PR. Please have a check.
