### ISSUE TITLE
Create dataset loader for Melayu_Brunei

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#207]
Dataloader name: `melayu_brunei/melayu_brunei.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?melayu_brunei

|     Dataset| melayu_brunei |
|-------------|---|
| Description | This article gives two texts of Brunei Malay (ISO 639-3: kxd) collected in the town of Weston in Sabah State of Malaysia. The texts exhibit linguistic features that are similar to those of Brunei Malay spoken in Brunei Darussalam; it has a vowel inventory of only three vowels /a, i, u/, use of the pronoun kitani for the first person plural inclusive and the use of the base-stem transitive form in patientive voice clauses. One of the texts tells a folk story about Batang Dayang and other text includes two episodes: Javanese runaways arriving in Weston and the origin of the name Bukau, a town near Weston. |
| Subsets | - |
| Languages | zlm, kxd |
| Tasks | Language Modeling |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/matbahasa/Melayu_Brunei |
| HF URL | - |
| Paper URL | https://tufs.repo.nii.ac.jp/records/1594 |

**Comment by Alex-HaochenLi** [comment]
#self-assign

**Comment by Alex-HaochenLi** [comment]
Have submitted a PR. 

I want to report that this dataset contains only Brunei. No Melayu is included.

**Comment by sabilmakbar** [comment]
Hi, it looks like we need to rectify the lang label by removing `zlm` since I don't find any reference to it either.
