### ISSUE TITLE
Create dataset loader for Vietnamese Students' Feedback Corpus (UIT-VSFC)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#208]
Dataloader name: `uit_vsfc/uit_vsfc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit_vsfc

|     Dataset| uit_vsfc |
|-------------|---|
| Description | This corpus consists of student feedback obtained from end-of-semester surveys at a Vietnamese university. Feedback is classified into four possible topics: lecturer, curriculum, facility or others. Feedback is also labeled as one of three sentiment polarities: positive, negative or neutral. |
| Subsets | - |
| Languages | vie |
| Tasks | Topic Modeling, Sentiment Analysis |
| License | Unknown (unknown) |
| Homepage | https://drive.google.com/drive/folders/1HooABJyrddVGzll7fgkJ6VzkG_XuWfRu |
| HF URL | https://huggingface.co/datasets/uitnlp/vietnamese_students_feedback |
| Paper URL | https://ieeexplore.ieee.org/document/8573337 |

**Comment by Alex-HaochenLi** [comment]
#self-assign

**Comment by Alex-HaochenLi** [comment]
Hello @holylovenia @SamuelCahyawijaya @sabilmakbar, I have a problem.

This dataset can handle two tasks, topic modeling and sentiment analysis.
In schema definition, both of them belong to General Text Classification Schema.
However, I cannot define two same schemas at the same time. 
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/45845237/6256fc47-81c1-4b2f-b2b3-6ab9e6107d02)
I try to set two different names but it can not pass the unit tests.
Do you have some suggestions? Thanks for your help.

**Comment by Alex-HaochenLi** [comment]
> Hello @holylovenia @SamuelCahyawijaya @sabilmakbar, I have a problem.
> 
> This dataset can handle two tasks, topic modeling and sentiment analysis. In schema definition, both of them belong to General Text Classification Schema. However, I cannot define two same schemas at the same time. ![image](https://private-user-images.githubusercontent.com/45845237/292948419-6256fc47-81c1-4b2f-b2b3-6ab9e6107d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDY1NDksIm5iZiI6MTcwMzY0NjI0OSwicGF0aCI6Ii80NTg0NTIzNy8yOTI5NDg0MTktNjI1NmZjNDctODFjMS00YjJmLWIyYjMtNmFiOWU2MTA3ZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAzMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjM0MzA2NzhkOTA4NTBiMjU2ODE5M2ZhZTc4NDYyMDcyMWRjZTg2N2M3M2EzODAyYzMyNTRlYzJjNDU5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhq_mJMX9MgI5LhA_rTmrU8_WB_PqNfEnkVQhHxrQgk) I try to set two different names but it can not pass the unit tests. Do you have some suggestions? Thanks for your help.

After reading through the existing dataset files, I found that this is the first time of such a problem.

**Comment by holylovenia** [comment]
> Hello @holylovenia @SamuelCahyawijaya @sabilmakbar, I have a problem.
> 
> This dataset can handle two tasks, topic modeling and sentiment analysis. In schema definition, both of them belong to General Text Classification Schema. However, I cannot define two same schemas at the same time. ![image](https://private-user-images.githubusercontent.com/45845237/292948419-6256fc47-81c1-4b2f-b2b3-6ab9e6107d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTA5NjYsIm5iZiI6MTcwMzY5MDY2NiwicGF0aCI6Ii80NTg0NTIzNy8yOTI5NDg0MTktNjI1NmZjNDctODFjMS00YjJmLWIyYjMtNmFiOWU2MTA3ZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1MjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjhmZmFkMjUyYjBmY2Y4Y2Q2YzEzYjIxYjc0ZDE3YzZlMjI1NGRjNzcxNWFiN2U1ZDJkY2ZhZDA1OTFjMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t01OficwaCwpdxmSlHv3sGRFyKBeOl0FBnl3dHvYrFg) I try to set two different names but it can not pass the unit tests. Do you have some suggestions? Thanks for your help.

Hi @Alex-HaochenLi, thanks for letting us know. Could you please provide the output of the unit test so we can check?

**Comment by Alex-HaochenLi** [comment]
Hi @holylovenia, just like the figure I provided above, I define two separate configs, one for topic modeling and the other one for sentiment analysis. They all belong to the schema of "TEXT". To distinguish them, they have different names.

The error message of unit tests is shown below.
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/45845237/8409dd90-e55f-4c1b-8f7f-593907814392)

We could see that during testing, the test config tried to match the name of the defined configs but failed.

**Comment by sabilmakbar** [comment]
For this, there are two things that we should do:
1. Define the config name as `uit_vsfc_topic_seacrowd_text` or `uit_vsfc_sentiment_seacrowd_text` (same goes to its `source` implementation).
2. To pass the test, you can use `--subset_id` args in the test script so that the config name will look as follows:
`{subset_id}_{source/seacrowd}_{config_suffix}`

let me know if you need more help on this

**Comment by Alex-HaochenLi** [comment]
> For this, there are two things that we should do:
> 
> 1. Define the config name as `uit_vsfc_topic_seacrowd_text` or `uit_vsfc_sentiment_seacrowd_text` (same goes to its `source` implementation).
> 2. To pass the test, you can use `--subset_id` args in the test script so that the config name will look as follows:
>    `{subset_id}_{source/seacrowd}_{config_suffix}`
> 
> Apologies for not putting a throughout doc on this, let me know if you need more help on the implementation.

Thank you for your help! Now I can pass the unit tests with argument specification.
Have submitted a PR for the implementation of dataloader. Please have a check.

**Comment by sabilmakbar** [comment]
Cool! It'd be better to give the Python CLI command asw on your PR so the reviewer can test it easier. Thanks for the help, @Alex-HaochenLi!

**Comment by Alex-HaochenLi** [comment]
> Cool! It'd be better to give the Python CLI command asw on your PR so the reviewer can test it easier. Thanks for the help, @Alex-HaochenLi!

Thank you for your suggestion. I have added the command information to my PR.
