### ISSUE TITLE
Create dataset loader for Vietnamese Social Media Emotion Corpus (UIT-VSMEC)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#209]
Dataloader name: `uit_vsmec/uit_vsmec.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit_vsmec

|     Dataset| uit_vsmec |
|-------------|---|
| Description | This dataset consists of Vietnamese Facebook comments that were manually annotated for sentiment. There are seven possible emotion labels: enjoyment, sadness, fear, anger, disgust, surprise or other (for comments with no or neutral emotions).  Two rounds of manual annotations were done to train annotators with tagging and editing guidelines. Annotation was performed until inter-annotator agreement reached at least 80%. |
| Subsets | - |
| Languages | vie |
| Tasks | Emotion Classification |
| License | Unknown (unknown) |
| Homepage | https://drive.google.com/drive/folders/1HooABJyrddVGzll7fgkJ6VzkG_XuWfRu |
| HF URL | https://huggingface.co/datasets/duwuonline/UIT-VSMEC/tree/main |
| Paper URL | https://arxiv.org/pdf/1911.09339.pdf |

**Comment by jen-santoso** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Not sure why the homepage is a GDrive link when the dataset has HF Dataset link...
