### ISSUE TITLE
Create dataset loader for Orchid Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#210]
Dataloader name: `orchid_pos/orchid_pos.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?orchid_pos

|     Dataset| orchid_pos |
|-------------|---|
| Description | The ORCHID corpus is a Thai part-of-speech (POS) tagged dataset, resulting from a collaboration between Japan's Communications Research Laboratory (CRL) and Thailand's National Electronics and Computer Technology Center (NECTEC). It is structured at three levels: paragraph, sentence, and word. The dataset incorporates a unique tagset designed for use in multi-lingual machine translation projects, and is tailored to address the challenges of Thai text, which lacks explicit word and sentence boundaries, punctuation, and inflection. This dataset includes text information along with numbering for retrieval, and employs a probabilistic trigram model for word segmentation and POS tagging. The ORCHID corpus is specifically structured to reduce ambiguity in POS assignments, making it a valuable resource for Thai language processing and computational linguistics research. |
| Subsets | - |
| Languages | tha |
| Tasks | POS Tagging |
| License | Creative Commons Attribution Non Commercial Share Alike 3.0 (cc-by-nc-sa-3.0) |
| Homepage | https://github.com/wannaphong/corpus_mirror/releases/tag/orchid-v1.0 |
| HF URL | - |
| Paper URL | https://www.jstage.jst.go.jp/article/ast1980/20/3/20_3_189/_pdf/-char/en |

**Comment by MJonibek** [comment]
#self-assign
