### ISSUE TITLE
Create dataset loader for Thai-Alpaca

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#212]
Dataloader name: `thai_alpaca/thai_alpaca.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_alpaca

|     Dataset| thai_alpaca |
|-------------|---|
| Description | This is a Thai-instructed dataset translated from cleaned version of the original Alpaca Dataset released by Stanford using Google Cloud Translation, contain 52,000 instructions and demonstrations generated by OpenAI's text-davinci-003 engine. This instruction data can be used to conduct instruction-tuning for language models and make the language model follow instruction better. |
| Subsets | - |
| Languages | tha |
| Tasks | Chatbot, Language Modeling |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://huggingface.co/datasets/Thaweewat/alpaca-cleaned-52k-th |
| HF URL | https://huggingface.co/datasets/Thaweewat/alpaca-cleaned-52k-th |
| Paper URL | - |

**Comment by yana-xuyan** [comment]
＃self-assign

**Comment by yana-xuyan** [comment]
#self-assign
