### ISSUE TITLE
Create dataset loader for Thai Databricks Dolly

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#213]
Dataloader name: `thai_databricks_dolly/thai_databricks_dolly.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_databricks_dolly

|     Dataset| thai_databricks_dolly |
|-------------|---|
| Description | This is a Thai-instructed dataset translated from databricks-dolly-15k using Google Cloud Translation. databricks-dolly-15k is an open-source dataset of instruction-following records generated by thousands of Databricks employees in several behavioral categories outlined in the InstructGPT paper, including brainstorming, classification, closed QA, generation, information extraction, open QA, and summarization. |
| Subsets | - |
| Languages | tha |
| Tasks | Chatbot, Language Modeling |
| License | Creative Commons Attribution Share Alike 3.0 (cc-by-sa-3.0) |
| Homepage | https://huggingface.co/datasets/Thaweewat/databricks-dolly-15k-th |
| HF URL | https://huggingface.co/datasets/Thaweewat/databricks-dolly-15k-th |
| Paper URL | - |

**Comment by ljvmiranda921** [comment]
#self-assign
