### ISSUE TITLE
Create dataset loader for Thai HH-RLHF

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#214]
Dataloader name: `thai_hh_rlhf/thai_hh_rlhf.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_hh_rlhf

|     Dataset| thai_hh_rlhf |
|-------------|---|
| Description | This is a ?? Thai-translated dataset based on Anthropic/hh-rlhf using Google Cloud Translation. This repository provides access to 161K Train dataset Anthropic/hh-rlhf (Thai-translated) |
| Subsets | - |
| Languages | tha |
| Tasks | Chatbot, Language Modeling |
| License | MIT (mit) |
| Homepage | https://huggingface.co/datasets/Thaweewat/hh-rlhf-th |
| HF URL | https://huggingface.co/datasets/Thaweewat/hh-rlhf-th |
| Paper URL | - |

**Comment by yana-xuyan** [comment]
#self-assign
