### ISSUE TITLE
Create dataset loader for Thai GPTeacher

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#215]
Dataloader name: `thai_gpteacher/thai_gpteacher.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_gpteacher

|     Dataset| thai_gpteacher |
|-------------|---|
| Description | This is a Thai-instructed dataset translated using Google Cloud Translation from GPTeacher, A collection of modular datasets generated by GPT-4, General-Instruct & Roleplay-Instruct and is comprised of around 20,000 examples with deduplication. The dataset was asked to include reasoning and thought steps in the example responses where appropriate. |
| Subsets | - |
| Languages | tha |
| Tasks | Chatbot, Language Modeling |
| License | MIT (mit) |
| Homepage | https://huggingface.co/datasets/Thaweewat/gpteacher-20k-th |
| HF URL | https://huggingface.co/datasets/Thaweewat/gpteacher-20k-th |
| Paper URL | - |

**Comment by chenxwh** [comment]
#self-assign
