### ISSUE TITLE
Create dataset loader for Mozilla Pontoon Translations

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#216]
Dataloader name: `mozilla_pontoon/mozilla_pontoon.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mozilla_pontoon

|     Dataset| mozilla_pontoon |
|-------------|---|
| Description | This is a dataset containing translations from Mozilla's Pontoon localization platform for more than 200 languages. Source sentences are in English. https://pontoon.mozilla.org/teams/ |
| Subsets | Burmese - English, Cebuano - English, Gorontalo - English, Hiligaynon - English, Ilocano - English, Indonesian - English, Javanese - English, Khmer - English, Lao - English, Malay - English, Nias - English, Tagalog - English, Thai - English, Vietnamnese - English |
| Languages | mya, ceb, gor, hil, ilo, ind, jav, khm, lao, zlm, nia, tgl, tha, vie |
| Tasks | Machine Translation |
| License | BSD 3-clause “New” or “Revised” license (bsd-3-clause) |
| Homepage | https://huggingface.co/datasets/ayymen/Pontoon-Translations |
| HF URL | https://huggingface.co/datasets/ayymen/Pontoon-Translations |
| Paper URL | - |

**Comment by elyanah-aco** [comment]
#self-assign

**Comment by elyanah-aco** [comment]
@holylovenia @SamuelCahyawijaya @sabilmakbar

Some points after checking the HF URL and platform:
- Pontoon itself is just a localization platform for different Mozilla projects, including CommonVoice (issue #141). It's not indicated which project each entry comes from in the HF data.
- Translations may be obtained from individual project Github repos. They cannot be obtained from the [Pontoon Github repo](https://github.com/mozilla/pontoon). 
- You can download translations from the Pontoon platform, but not in the same format as in the HF URL. Formats may also differ per project. 
- The dataset uploader seems to be a Pontoon contributor (but not a major one). The dataset was last updated within the last month. 

I think there are two ways to go about this:
1. Implement dataloaders for any valid individual project
2. Continue with the HF data and just note any possible issues with data quality, overlap, timeliness, etc.

I think we can do the 2nd option but what do you think?

**Comment by holylovenia** [comment]
Hi @elyanah-aco, thanks for noting down these points. Let's go with the second option.
