### ISSUE TITLE
Create dataset loader for Tagalog Profanity Dataset

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#220]
Dataloader name: `tgl_profanity/tgl_profanity.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tgl_profanity

|     Dataset| tgl_profanity |
|-------------|---|
| Description | This dataset contains 13.8k Tagalog sentences containing profane words, together with binary labels denoting whether or not the sentence conveys profanity / abuse / hate speech. The data was scraped from Twitter using a Python library called SNScrape and annotated manually by a panel of native Filipino speakers. |
| Subsets | - |
| Languages | tgl |
| Tasks | Abusive Language Detection, Hate Speech Detection, Text Classification |
| License | Unknown (unknown) |
| Homepage | https://huggingface.co/datasets/mginoben/tagalog-profanity-dataset |
| HF URL | https://huggingface.co/datasets/mginoben/tagalog-profanity-dataset |
| Paper URL | https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4341604 |

**Comment by ljvmiranda921** [comment]
#self-assign
