### ISSUE TITLE
Create dataset loader for CreoleRC

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#222]
Dataloader name: `creole_rc/creole_rc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?creole_rc

|     Dataset| creole_rc |
|-------------|---|
| Description | CreoleRC is a subset created by the CreoleVal paper. Relation classification (RC) aims to identify semantic associations between entities within a text, essential for applications like knowledge base completion and question answering. The dataset is sourced from Wikipedia and manually annotated. CreoleRC contains 5 creoles, but SEACrowd is interested specifically in the Chavacano subset. |
| Subsets | - |
| Languages | cbk |
| Tasks | Relation Extraction |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/hclent/CreoleVal/tree/main/nlu/relation_classification |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2310.19567 |

**Comment by sedrickkeh** [comment]
#self-assign

**Comment by sedrickkeh** [comment]
Working on it. Will try to finish this week

**Comment by zwenyu** [comment]
#self-assign
