### ISSUE TITLE
Create dataset loader for VinText

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#223]
Dataloader name: `vintext/vintext.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vintext

|     Dataset| vintext |
|-------------|---|
| Description | Vintext is a challenging scene text dataset for Vietnamese, where some characters are equivocal in the visual form due to accent symbols. This dataset contains 2000 fully annotated images with 56,084 text instances. Each text instance is delineated by a quadrilateral bounding box and associated with the ground truth sequence of characters. The dataset is randomly split into three subsets for training (1,200 images), validation (300 images), and testing (500 images). |
| Subsets | - |
| Languages | vie |
| Tasks | Optical Character Recognition |
| License | GNU Affero General Public License v3.0 (agpl-3.0) |
| Homepage | https://github.com/VinAIResearch/dict-guided |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/9577624 |

**Comment by sedrickkeh** [comment]
#self-assign

**Comment by sedrickkeh** [comment]
Working on it. Will try to finish this week

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by patrickamadeus** [comment]
#self-assign
