### ISSUE TITLE
Create dataset loader for KVIS Thai OCR

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#224]
Dataloader name: `kvis_th_ocr/kvis_th_ocr.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?kvis_th_ocr

|     Dataset| kvis_th_ocr |
|-------------|---|
| Description | The KVIS Thai OCR Dataset contains scanned handwritten version of all 44 Thai characters obtained from 27 individuals. It consisted of 1079 images from 44 classes (letters). This dataset consists of all Thai consonants with different writing styles of various people from ages between 16 and 75. Vowels and intonation are not taken into consideration for the dataset collected. |
| Subsets | - |
| Languages | tha |
| Tasks | Optical Character Recognition |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | http://dx.doi.org/10.17632/8nr3pbdk5c.1 |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/8584876 |

**Comment by sedrickkeh** [comment]
#self-assign

**Comment by sedrickkeh** [comment]
Working on it. Will try to finish this week
