### ISSUE TITLE
Create dataset loader for ALICE-THI

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#225]
Dataloader name: `alice-thi/alice-thi.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?alice-thi

|     Dataset| alice-thi |
|-------------|---|
| Description | ALICE-THI is a Thai handwritten script dataset that contains 24045 character images, which is split into Thai handwritten character dataset (THI-C68) for 14490 images and Thai handwritten digit dataset (THI-D10) for 9555 images. The data was collected from 150 native writers aged from 20 to 23 years old. The participants were allowed to write only the isolated Thai script on the form and at least 100 samples per character. The character images obtained from this dataset generally have no background noise. |
| Subsets | THI-C68, THI-D10 |
| Languages | tha |
| Tasks | Optical Character Recognition |
| License | Unknown (unknown) |
| Homepage | https://www.ai.rug.nl/~mrolarik/ALICE-THI/ |
| HF URL | - |
| Paper URL | https://www.sciencedirect.com/science/article/abs/pii/S0952197615001724 |

**Comment by sedrickkeh** [comment]
#self-assign

**Comment by sedrickkeh** [comment]
Working on it. Will try to finish this week

**Comment by holylovenia** [comment]
> Working on it. Will try to finish this week

No problem. Feel free to let us know if you have any question.

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
#self-assign
