### ISSUE TITLE
Create dataset loader for Vi Pubmed

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#226]
Dataloader name: `vi_pubmed/vi_pubmed.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vi_pubmed

|     Dataset| vi_pubmed |
|-------------|---|
| Description | Vi Pubmed (or Vietnamese Pubmed) is a corpus of PubMed biomedical abstracts translated by the state-of-the-art English-Vietnamese Translation project. The data has been used as unlabeled dataset for pretraining a Vietnamese Biomedical-domain Transformer model. |
| Subsets | - |
| Languages | vie |
| Tasks | Machine Translation |
| License | Other (other) |
| Homepage | https://huggingface.co/datasets/VietAI/vi_pubmed |
| HF URL | https://huggingface.co/datasets/VietAI/vi_pubmed |
| Paper URL | https://aclanthology.org/2023.eacl-main.228/ |

**Comment by ljvmiranda921** [comment]
#self-assign

**Comment by dovanquyet** [comment]
#self-assign

**Comment by ljvmiranda921** [comment]
Feel free to get this @dovanquyet :)

**Comment by dovanquyet** [comment]
sure, thanks

**Comment by Enliven26** [comment]
#self-assign
