### ISSUE TITLE
Create dataset loader for UIT-ViIC

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#227]
Dataloader name: `uit-viic/uit-viic.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit-viic

|     Dataset| uit-viic |
|-------------|---|
| Description | UIT-ViIC contains manually written captions for images from Microsoft COCO dataset relating to sports played with ball. UIT-ViIC consists of 19,250 Vietnamese captions for 3,850 images. For each image, UIT-ViIC provides five Vietnamese captions annotated by five annotators. |
| Subsets | - |
| Languages | vie |
| Tasks | Image-to-Text Generation |
| License | Unknown (unknown) |
| Homepage | https://drive.google.com/file/d/1YexKrE6o0UiJhFWpE8M5LKoe6-k3AiM4 |
| HF URL | - |
| Paper URL | https://link.springer.com/chapter/10.1007/978-3-030-63007-2_57 |

**Comment by Gyyz** [comment]
#self-assign
