### ISSUE TITLE
Create dataset loader for CebuaNER

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#23]
Dataloader name: `cebuaner/cebuaner.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?cebuaner

|     Dataset| cebuaner |
|-------------|---|
| Description | The CebuaNER dataset contains 4000+ news articles that have been tagged by native speakers of Cebuano using the BIO encoding schema for the named entity recognition (NER) task. |
| Subsets | - |
| Languages | ceb |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/mebzmoren/CebuaNER |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2310.00679v1 |

**Comment by ljvmiranda921** [comment]
I can help with this :)

**Comment by ljvmiranda921** [comment]
#self-assign
