### ISSUE TITLE
Create dataset loader for BasahaCorpus

### ISSUE THREAD

**Issue by holylovenia** [SEACrowd/seacrowd-datahub#26]
Dataloader name: `basaha_corpus/basaha_corpus.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?basaha_corpus

|     Dataset| basaha_corpus |
|-------------|---|
| Description | BasahaCorpus contains short stories in four Central Philippine languages (Minasbate, Rinconada, Kinaray-a, and Hiligaynon) for low-resource readability assessment. Each dataset per language contains stories distributed over the first three grade levels (L1, L2, and L3) in the Philippine education context. The grade levels of the dataset have been provided by an expert from Let's Read Asia. |
| Subsets | - |
| Languages | bto, krj, hil, msb |
| Tasks | Readibility Assessment |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/imperialite/BasahaCorpus-HierarchicalCrosslingualARA |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2310.11584 |

**Comment by athayahisyam** [comment]
#self-assign

**Comment by athayahisyam** [comment]
Hello, thank you very much for the reminder, I am still learning about creating data loader. Kindly remind me if there is a deadline that I should aware of. Thank you.

**Comment by holylovenia** [comment]
@athayahisyam Amazing! No problem at all, we're just checking every now and then. 👍 Just let us know if you have any questions.

**Comment by sabilmakbar** [comment]
Hi @athayahisyam, May I know if you have an estimated completion date for this? The expected working period is ~1 month (2 weeks warning and another 2 weeks prior to assignation removal if no activities, like qn, discussion, progress notification, or PR, are recorded). But we may consider the extension on a case-by-case basis. I'd be more than happy to help if you'd like more guidance on how to create this dataloader, tho.

**Comment by athayahisyam** [comment]
Hi, that would be helpful. Is there any literature or clear tutorial on this? I failed to understand the how-to on the internet except for the definition that a dataloader is a software/package that helps dataset users by loading them into the system (like anaconda or colaboratory) simply by typing some command (like `kaggle -download`) and then the dataset is downloaded and ready to be put in `df` variable. Is that correct?

I am sorry for the slow progress. If it gets nowhere, I will drop the assignment. I apologize for this inconvenience and for creating a setback in the project.

**Comment by sabilmakbar** [comment]
You may start from reading HuggingFace Dataloader Creation in [here](https://huggingface.co/docs/datasets/dataset_script), or start via this [Markdown info](https://github.com/SEACrowd/seacrowd-datahub/blob/master/DATALOADER.md)

**Comment by sabilmakbar** [comment]
Hi @athayahisyam, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by athayahisyam** [comment]
Hi, it seems that I could not get anywhere even with the tutorial. I've encountered some issues with my OS that left me stuck for some days. 

Please unassign me from the task. 

In the mean time, I will try to work on the loader separately, and will add them later, if the issue is still open. 
Thank  you for the opportunity, and I apologize for the inconvenience and if I slowed down the team.

**Comment by sabilmakbar** [comment]
okay, feel free to ping me over the discord for any help or inquiries.

**Comment by Enliven26** [comment]
#self-assign

**Comment by Enliven26** [comment]
I have created 3 PR request and willing to create more data loader but I am not sure if the previous ones that I made is correct. May I get review on one of my PRs (#389, #390, #391)? Thanks

**Comment by holylovenia** [comment]
Hi @Enliven26, thanks a lot for your contributions! We're currently trying our best to catch up with the incoming PRs. 🙏

**Comment by holylovenia** [comment]
Hi @Enliven26, may I know if you are still working on this issue?

**Comment by muhammadravi251001** [comment]
#self-assign
