### ISSUE TITLE
Create dataset loader for Myanmar-Rakhine Parallel Data

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#262]
Dataloader name: `myanmar_rakhine_parallel/myanmar_rakhine_parallel.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?myanmar_rakhine_parallel

|     Dataset| myanmar_rakhine_parallel |
|-------------|---|
| Description | The data contains 18,373 Myanmar sentences of the ASEAN-MT Parallel Corpus, which is a parallel corpus in the travel domain. It contains six main categories: people (greeting, introduction, and communication), survival (transportation, accommodation, and finance), food (food, beverages, and restaurants), fun (recreation, traveling, shopping, and nightlife), resource (number, time, and accuracy), special needs (emergency and health). Manual translation into the Rakhine language was done by native Rakhine students from two Myanmar universities, and the translated corpus was checked by the editor of a Rakhine newspaper. Word segmentation for Rakhine was done manually, and there are exactly 123,018 words in total. |
| Subsets | - |
| Languages | mya, rki |
| Tasks | Machine Translation |
| License | GNU General Public License v3.0 (gpl-3.0) |
| Homepage | https://github.com/ye-kyaw-thu/myPar/tree/master/my-rk |
| HF URL | - |
| Paper URL | https://aclanthology.org/W19-1408/ |

**Comment by muhsatrio** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @muhsatrio, may we know the update on this dataloader issue? It's been 2 weeks since the last poke from the SEACrowd stale-checker, and we might consider unassigning if there's no progress update in the next 24 hours.

**Comment by zwenyu** [comment]
#self-assign
