### ISSUE TITLE
Create dataset loader for VIVOS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#263]
Dataloader name: `vivos/vivos.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vivos

|     Dataset| vivos |
|-------------|---|
| Description | VIVOS is a free Vietnamese speech corpus consisting of 15 hours of recording speech prepared for Automatic Speech Recognition task. This speech corpus is collected by recording speech data from more than 50 native Vietnamese volunteers. The speech was recorded in a quiet environment with high quality microphone. |
| Subsets | - |
| Languages | vie |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://zenodo.org/records/7068130 |
| HF URL | https://huggingface.co/datasets/vivos |
| Paper URL | https://aclanthology.org/W16-5207/ |

**Comment by danjohnvelasco** [comment]
#self-assign

**Comment by raileymontalan** [comment]
#self-assign

**Comment by raileymontalan** [comment]
Latest nitpicks have been resolved, should be PR ready.
