### ISSUE TITLE
Create dataset loader for myXNLI

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#265]
Dataloader name: `myxnli/myxnli.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?myxnli

|     Dataset| myxnli |
|-------------|---|
| Description | The myXNLI corpus is a collection of Myanmar language data designed for the Natural Language Inference (NLI) task, which originated from the XNLI and MultiNLI English datasets. The 7,500 sentence pairs from the XNLI English development and test sets are human-translated into Myanmar. The 392,702 data from the NLI English training data is translated using machine translation. In addition, it also extends its scope by adding Myanmar translations to the XNLI 15-language parallel corpus, to create a 16-language parallel corpus. |
| Subsets | - |
| Languages | mya |
| Tasks | Natural Language Inference |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/akhtet/myXNLI |
| HF URL | https://huggingface.co/datasets/akhtet/myXNLI |
| Paper URL | - |

**Comment by chenxwh** [comment]
#self-assign

**Comment by chenxwh** [comment]
> Hi, may I know if you are still working on this issue? Please let @holylovenia @SamuelCahyawijaya @sabilmakbar know if you need any help.

@sabilmakbar PR already submitted but just got the msg from "gitbub-actions"
