### ISSUE TITLE
Create dataset loader for Thai Toxicity Tweet Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#268]
Dataloader name: `thai_toxicity_tweet/thai_toxicity_tweet.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_toxicity_tweet

|     Dataset| thai_toxicity_tweet |
|-------------|---|
| Description | Thai Toxicity Tweet Corpus contains 3,300 tweets (506 tweets with texts missing) annotated by humans with guidelines including a 44-word dictionary. The author acquired 2,027 toxic and 1,273 non-toxic tweets, which were manually labeled by three annotators. Toxicity is defined by the author as any message conveying harmful, damaging, or negative intent, in accordance with their defined criteria for toxicity. |
| Subsets | - |
| Languages | tha |
| Tasks | Text Classification |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/tmu-nlp/ThaiToxicityTweetCorpus/ |
| HF URL | https://huggingface.co/datasets/thai_toxicity_tweet |
| Paper URL | https://www.ta-cos.org/sites/ta-cos.org/files/1_W32.pdf |

**Comment by elyanah-aco** [comment]
#self-assign

**Comment by elyanah-aco** [comment]
@holylovenia Not sure if any of the current tasks suit this dataset, maybe adding something like `HATE_CLASSIFICATION` or `TOXICITY_CLASSIFICATION` would work?
