### ISSUE TITLE
Create dataset loader for ViVQA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#269]
Dataloader name: `vivqa/vivqa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vivqa

|     Dataset| vivqa |
|-------------|---|
| Description | Vietnamese Visual Question Answering (ViVQA) consist of 10328 images and 15000 question-answer pairs in Vietnamese for evaluating Vietnamese VQA models. This dataset is built based on 10328 randomly selected images from MS COCO dataset. The question-answer pairs were based on the COCO-QA dataset that was automatically translated from English to Vietnamese. |
| Subsets | - |
| Languages | vie |
| Tasks | Question Answering |
| License | Unknown (unknown) |
| Homepage | https://github.com/kh4nh12/ViVQA |
| HF URL | - |
| Paper URL | https://aclanthology.org/2021.paclic-1.72.pdf |

**Comment by Gyyz** [comment]
#self-assign
