### ISSUE TITLE
Create dataset loader for SNLI Indo

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#272]
Dataloader name: `snli-indo/snli-indo.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?snli-indo

|     Dataset| snli-indo |
|-------------|---|
| Description | The SNLI Indo dataset is derived from the SNLI corpus by translating each premise and hypothesis sentence from English to Indonesia via the Google Cloud Translation API.   Premise sentences are crawled image captions from Flickr, and hypothesis sentences are manually created through crowdsourcing. Five annotators are assigned per sentence pair to label the inference relationship as entailment (true), contradiction (false) or neutral (undetermined). |
| Subsets | - |
| Languages | ind |
| Tasks | Semantic Textual Similarity |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://data.mendeley.com/datasets/k4tjhzs2gd/1 |
| HF URL | - |
| Paper URL | https://www.sciencedirect.com/science/article/pii/S2352340923010284 |

**Comment by khelli07** [comment]
#self-assign
