### ISSUE TITLE
Create dataset loader for UIT-ViON

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#273]
Dataloader name: `uit_vion/uit_vion.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit_vion

|     Dataset| uit_vion |
|-------------|---|
| Description | UIT-ViON (Vietnamese Online Newspaper) is a dataset collected from well-known online newspapers in Vietnamese. The UIT-ViON is an open-domain, large-scale, and high-quality dataset consisting of 260,000 textual data points annotated with 13 different categories for evaluating Vietnamese short text classification. The dataset is split into training, validation, and test sets, each containing 208000, 26000, and 26000 pieces of text, respectively. |
| Subsets | - |
| Languages | vie |
| Tasks | Text Classification |
| License | Unknown (unknown) |
| Homepage | https://github.com/kh4nh12/UIT-ViON-Dataset |
| HF URL | - |
| Paper URL | https://ebooks.iospress.nl/DOI/10.3233/FAIA210036 |

**Comment by Alex-HaochenLi** [comment]
#self-assign
