### ISSUE TITLE
Create dataset loader for OIL

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#274]
Dataloader name: `oil/oil.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?oil

|     Dataset| oil |
|-------------|---|
| Description | The Online Indonesian Learning (OIL) dataset or corpus contains lessons from three Indonesian teachers who have posted content on YouTube. "Noisy" data, such as background noise, accented speech, task specific intonation/articulation, and frequent language mixing, was kept to provide realistic insight into the performance of ASR for the real-world task of converting teacher speech from YouTube into searchable text. Initial transcription was completed by the first author, who is an Indonesian-English bilingual, teacher, and linguist. |
| Subsets | - |
| Languages | ind, eng |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://huggingface.co/datasets/ZMaxwell-Smith/OIL |
| HF URL | https://huggingface.co/datasets/ZMaxwell-Smith/OIL |
| Paper URL | https://aclanthology.org/2023.fieldmatters-1.1.pdf |

**Comment by Gyyz** [comment]
#self-assign

**Comment by Enliven26** [comment]
#self-assign

**Comment by Enliven26** [comment]
Going to make a PR

**Comment by Enliven26** [comment]
created a pull request
