### ISSUE TITLE
Create dataset loader for SEA Wikipedia

### ISSUE THREAD

**Issue by holylovenia** [SEACrowd/seacrowd-datahub#28]
Dataloader name: `sea_wiki/sea_wiki.py`
DataCatalogue: https://seacrowd.github.io/seacrowd-catalogue/card.html?SEA%20Wikipedia

|     Dataset| sea_wiki |
|-------------|---|
| Description | SEA Lang & Local Langs Wikipedia Archives, dumped from WIkipedia HF and processed by boilerplate removal. This dataset consists of URL of referred Wikipedia Article, its Title, and its Text Data (Article Contents). |
| Subsets | ace, ban, bcl, bjn, bug, cbk_zam, gor, id, ilo, jv, km, lo, mad, map_bms, min, mnw, ms, nia, pag, pam, shn, su, tet, th, tl, vi, war |
| Languages | ace, ban, bcl, bjn, bug, cbk, gor, ilo, ind, jav, khm, lao, mad, min, mnw, mya, nia, pag, pam, shn, sun, tet, tgl, tha, vie, war |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://huggingface.co/datasets/sabilmakbar/sea_wiki |
| HF URL | https://huggingface.co/datasets/sabilmakbar/sea_wiki |
| Paper URL | No publication |

**Comment by sabilmakbar** [comment]
Working on this issue, ETA tomorrow evening

**Comment by sabilmakbar** [comment]
#self-assign
