### ISSUE TITLE
Create dataset loader for XQuAD

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#3]
Dataloader name: `xquad/xquad.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xquad

|     Dataset| xquad |
|-------------|---|
| Description | XQuAD (Cross-lingual Question Answering Dataset) is a benchmark dataset for evaluating cross-lingual question answering performance. The dataset consists of a subset of 240 paragraphs and 1190 question-answer pairs from the development set of SQuAD v1.1 (Rajpurkar et al., 2016) together with their professional translations into ten languages: Spanish, German, Greek, Russian, Turkish, Arabic, Vietnamese, Thai, Chinese, and Hindi. Consequently, the dataset is entirely parallel across 11 languages. |
| Subsets | xquad.th, xquad.vi |
| Languages | tha, vie |
| Tasks | Question Answering |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/google-deepmind/xquad |
| HF URL | https://huggingface.co/datasets/xquad |
| Paper URL | https://aclanthology.org/2020.acl-main.421/ |

**Comment by ilhamfp** [comment]
#self-assign
