### ISSUE TITLE
Create dataset loader for PALITO Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#30]
Dataloader name: `palito/palito.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?palito

|     Dataset| palito |
|-------------|---|
| Description | The PALITO Corpus is a compilation of multilingual written texts in four Philippine languages: Tagalog, Cebuano, Ilocano, and Hiligaynon. The categories of the corpus are mostly between literary or creative writing texts (such as novels and stories) and religious texts (such as the Bible). The overall corpus contains about 150,000 words from the literary texts and 100,000 words from the religious texts, with a total of 250,000. Previous works have used the corpus for language modeling and language identification. |
| Subsets | - |
| Languages | tgl, ceb, ilo, hil, pag, pam, war, bcl |
| Tasks | Language Modeling, Language Identification |
| License | GNU Lesser General Public License family (lgpl) |
| Homepage | https://github.com/imperialite/Philippine-Languages-Online-Corpora/tree/master/PALITO%20Corpus |
| HF URL | - |
| Paper URL | https://aclanthology.org/Y09-2024/ |

**Comment by ilhamfp** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @ilhamfp, may I know the current status of this dataloader creation? Feel free to discuss here if you have any difficulties. Thanks!

**Comment by ilhamfp** [comment]
Currently drafting a PR for it :D
