### ISSUE TITLE
Create dataset loader for Vietnamese Hate Speech Detection (UIT-ViHSD)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#309]
Dataloader name: `uit_vihsd/uit_vihsd.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit_vihsd

|     Dataset| uit_vihsd |
|-------------|---|
| Description | The ViHSD dataset consists of comments collected from Facebook pages and YouTube channels that have a high-interactive rate, and do not restrict comments. This dataset is used for hate speech detection on Vietnamese language. Data is anonymized, and labeled as either HATE, OFFENSIVE, or CLEAN. |
| Subsets | - |
| Languages | vie |
| Tasks | Hate Speech Detection |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/sonlam1102/vihsd/ |
| HF URL | - |
| Paper URL | https://link.springer.com/chapter/10.1007/978-3-030-79457-6_35 |

**Comment by Gyyz** [comment]
#self-assign

**Comment by Gyyz** [comment]
I am in China and on vocation, don’t have a good network to access the github, will update the repo when back after 2.18.


From: github-actions[bot] ***@***.***>
Date: Thursday, 25 January 2024 at 10:09
To: SEACrowd/seacrowd-datahub ***@***.***>
Cc: Yuze GAO ***@***.***>, Assign ***@***.***>
Subject: Re: [SEACrowd/seacrowd-datahub] Create dataset loader for Vietnamese Hate Speech Detection (UIT-ViHSD) (Issue #309)

Hi, may I know if you are still working on this issue? Please let @holylovenia<https://github.com/holylovenia> @SamuelCahyawijaya<https://github.com/SamuelCahyawijaya> @sabilmakbar<https://github.com/sabilmakbar> know if you need any help.

**Comment by Gyyz** [comment]
> Hi @, may I know if you are still working on this issue? Please let [@holylovenia](https://github.com/holylovenia) [@SamuelCahyawijaya](https://github.com/SamuelCahyawijaya) [@sabilmakbar](https://github.com/sabilmakbar) know if you need any help.

Hi, am back from China, will create the dataloader shortly.
