### ISSUE TITLE
Create dataset loader for Fleurs

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#31]
Dataloader name: `fleurs/fleurs.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?fleurs

|     Dataset| fleurs |
|-------------|---|
| Description | Fleurs dataset is a part of XTREME-S benchmark to evaluate universal cross-lingual speech representations in many languages. Fleurs is used for two tasks: automatic speech recognition and speech classification. Fleurs covers 10 language native to Southeast Asian and other 3 major languages mostly spoken in few of Southeast Asia countries (Mandarin Chinese, Portuguese, and Tamil). |
| Subsets | Fleurs Burmese, Fleurs Cebuano, Fleurs Filipino, Fleurs Indonesian, Fleurs Javanese, Fleurs Khmer, Fleurs Lao, Fleurs Malay, Fleurs Thai, Fleurs Vietnamese |
| Languages | mya, ceb, fil, ind, jav, khm, lao, zlm, tha, vie, cmn, por, tam |
| Tasks | Automatic Speech Recognition, Language Identification |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://huggingface.co/datasets/google/xtreme_s |
| HF URL | https://huggingface.co/datasets/google/xtreme_s |
| Paper URL | https://www.isca-speech.org/archive/interspeech_2022/conneau22_interspeech.html |

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi, few qns:
1. Do I have to define the subset name as stated in the initial description or is it okay to alter it as long as each subset is identifiable? (e.g using its ISO 639-3 lang codes)
2. Some language codes aren't matched w/ defined subsets (like ```por (Portuguese)```, ```cmn (China Mandarin)```, and ```tam (Tamil)```. Should it be omitted?
4. Any default values if any SEACrowd defined schema isn't available on the data? or is it okay to leave it as No Value?

**Comment by sabilmakbar** [comment]
Hi, looks like Speech Classification Schema isn't available yet. May I create a new PR to add that schema first prior to PR-ing this dataloader?

@SamuelCahyawijaya @holylovenia

**Comment by SamuelCahyawijaya** [comment]
@sabilmakbar : Sorry for the late reply
1. Yeah, I think that should be fine
2. No need to add these languages
3. Thank you for implementing the new schema for this task 👍🏻

**Comment by SamuelCahyawijaya** [comment]
I removed the bonus, as the schema creation counted as a separate GitHub maintainer contribution.
cc @sabilmakbar  @holylovenia
