### ISSUE TITLE
Create dataset loader for ViSpamReviews

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#310]
Dataloader name: `vispamreviews/vispamreviews.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vispamreviews

|     Dataset| vispamreviews |
|-------------|---|
| Description | The dataset was collected from leading online shopping platforms in Vietnam. Some of the most recent selling products for each product category were selected and up to 15 reviews per product were collected. Each review was then labeled as either NO-SPAM, SPAM-1 (fake review), SPAM-2 (review on brand only), or SPAM-3 (irrelevant content). |
| Subsets | - |
| Languages | vie |
| Tasks | Text Classification |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/sonlam1102/vispamdetection/ |
| HF URL | - |
| Paper URL | https://link.springer.com/chapter/10.1007/978-3-031-21743-2_48 |

**Comment by Gyyz** [comment]
#self-assign

**Comment by Gyyz** [comment]
I am in China and on vocation, don’t have a good network to access the github, will update the repo when back after 2.18.


From: github-actions[bot] ***@***.***>
Date: Thursday, 25 January 2024 at 10:09
To: SEACrowd/seacrowd-datahub ***@***.***>
Cc: Yuze GAO ***@***.***>, Assign ***@***.***>
Subject: Re: [SEACrowd/seacrowd-datahub] Create dataset loader for ViSpamReviews (Issue #310)

Hi, may I know if you are still working on this issue? Please let @holylovenia<https://github.com/holylovenia> @SamuelCahyawijaya<https://github.com/SamuelCahyawijaya> @sabilmakbar<https://github.com/sabilmakbar> know if you need any help.

**Comment by Gyyz** [comment]
> Hi @, may I know if you are still working on this issue? Please let [@holylovenia](https://github.com/holylovenia) [@SamuelCahyawijaya](https://github.com/SamuelCahyawijaya) [@sabilmakbar](https://github.com/sabilmakbar) know if you need any help.

Hi, am back from China, will create the dataloader shortly.
