### ISSUE TITLE
Create dataset loader for Saltik

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#313]
Dataloader name: `saltik/saltik.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?saltik

|     Dataset| saltik |
|-------------|---|
| Description | Saltik is a dataset for benchmarking non-word error correction method accuracy in evaluating Indonesian words. It consists of 58,532 non-word errors generated from 3,000 of the most popular Indonesian words. |
| Subsets | - |
| Languages | ind |
| Tasks | Error Spelling Correction |
| License | GNU Affero General Public License v3.0 (agpl-3.0) |
| Homepage | https://github.com/ir-nlp-csui/saltik |
| HF URL | - |
| Paper URL | https://github.com/ir-nlp-csui/saltik/blob/main/README.md |

**Comment by TysonYu** [comment]
#self-assign
