### ISSUE TITLE
Create dataset loader for Indonesia-Chinese-MTRobustEval

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#314]
Dataloader name: `indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indonesia_chinese_mtrobusteval

|     Dataset| indonesia_chinese_mtrobusteval |
|-------------|---|
| Description | The dataset is curated for the purpose of evaluating the robustness of Neural Machine Translation (NMT) towards natural occuring noise (typo, slang, code switching, etc.). The dataset is crawled from Twitter, then pre-processed to obtain sentences with noise. The dataset consists of a thousand noisy sentences. The dataset is translated into Chinese manually as the benchmark for evaluating the robustness of NMT. |
| Subsets | - |
| Languages | ind, cmn |
| Tasks | Machine Translation |
| License | MIT (mit) |
| Homepage | https://github.com/supryzhu/Indonesia-Chinese-MTRobustEval |
| HF URL | - |
| Paper URL | - |

**Comment by TysonYu** [comment]
#self-assign

**Comment by supryzhu** [comment]
#self-assign

**Comment by SamuelCahyawijaya** [comment]
Hi @supryzhu, I am unassigning your account from the issue as is already assigned to @TysonYu. 
If you want to see the unassigned dataloader issues, you can check them on the [Github project](https://github.com/orgs/SEACrowd/projects/1/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Assignees).
