### ISSUE TITLE
Create dataset loader for XL-Sum

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#32]
Dataloader name: `xl_sum/xl_sum.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xl_sum

|     Dataset| xl_sum |
|-------------|---|
| Description | XL-Sum, a comprehensive and diverse dataset comprising 1 million professionally annotated article-summary pairs from BBC, was extracted using a set of carefully designed heuristics. The dataset covers 44 languages ranging from low to high-resource, including 4 indigenous languages spoken in Southeast Asia region. |
| Subsets | XL-Sum Burmese, XL-Sum Indonesian, XL-Sum Thai, XL-Sum Vietnamnese |
| Languages | mya, ind, tha, vie |
| Tasks | Abstractive Summarization |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/csebuetnlp/xl-sum |
| HF URL | https://huggingface.co/datasets/csebuetnlp/xlsum |
| Paper URL | https://aclanthology.org/2021.findings-acl.413/ |

**Comment by rmahendra** [comment]
#self-assign

**Comment by rmahendra** [comment]
Hi, I'm still willing to work on this issue. However, I am quite busy at this moment. I'll try to PR by the end of this month.

**Comment by holylovenia** [comment]
Okay then, @rmahendra. Feel free to let us know if you need any help!

**Comment by sabilmakbar** [comment]
Hi @rmahendra, have you got the time to implement this dataloader?

**Comment by sabilmakbar** [comment]
Btw we have `xl_sum` already in SEACrowd but only for ID-EN pair. Will extend that script to cover the others

**Comment by holylovenia** [comment]
Adding `top-priority` and `bonus+1` because we need this dataloader for the experiments.
