### ISSUE TITLE
Create dataset loader for PhoST

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#33]
Dataloader name: `phost/phost.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?phost

|     Dataset| phost |
|-------------|---|
| Description | PhoST is a high-quality and large-scale benchmark dataset for English-Vietnamese speech translation with 508 audio hours, consisting of 331K triplets of (sentence-lengthed audio, English source transcript sentence, Vietnamese target subtitle sentence). |
| Subsets | - |
| Languages | vie, eng |
| Tasks | Speech-to-Speech Translation |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://github.com/VinAIResearch/PhoST |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2208.04243 |

**Comment by IvanHalimP** [comment]
#self-assign
