### ISSUE TITLE
Data quality for thai alpaca

### ISSUE THREAD

**Issue by wannaphong** [SEACrowd/seacrowd-datahub#330]
Hello SEACrowd! I am a Thai native speaker. I found your project sumbit thai_alpaca to your project. I think you should delete this dataset from your project. The dataset doesn't look like human answer and translate from alpaca dataset. It has data quatily problem from machine translation.

**Comment by holylovenia** [comment]
@wannaphong Thanks for reaching out to us about this. So from what I've understood from Peerat, this dataset is basically non-sensical and doesn't make sense. We'll try to find a way going forward as well as avoid this occurrence from happening again.

**Comment by wannaphong** [comment]
@holylovenia Is dataset ok?

**Comment by holylovenia** [comment]
> @holylovenia Is dataset ok?

Hey @wannaphong, we rejected this dataset from our catalogue. Thanks for your warning. 🙏 The details can be seen [here](https://docs.google.com/spreadsheets/d/1ibbywsC1tQ_sLPX8bUAjC-vrTrUqZgZA46W_sxWw4Ss/edit?usp=sharing).
