### ISSUE TITLE
Create dataset loader for IndonesianNMT

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#338]
Dataloader name: `indonesiannmt/indonesiannmt.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indonesiannmt

|     Dataset| indonesiannmt |
|-------------|---|
| Description | Repository containing datasets for data automatically generated from gpt-3.5-turbo and text-davinci-003 used in the work "Replicable Benchmarking of Neural Machine Translation (NMT) on Low-Resource Local Languages in Indonesia" |
| Subsets | - |
| Languages | ind, jav, min, sun, ban |
| Tasks | Machine Translation |
| License | Unknown (unknown) |
| Homepage | https://github.com/luckysusanto/IndonesianNMT |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2311.00998 |

**Comment by luckysusanto** [comment]
#self-assign
