### ISSUE TITLE
Create dataset loader for MKQA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#34]
Dataloader name: `mkqa/mkqa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mkqa

|     Dataset| mkqa |
|-------------|---|
| Description | MKQA, an open-domain question answering evaluation set comprising 10k question-answer pairs aligned across 26 typologically diverse languages (260k question-answer pairs in total), including 4 Southeast Asian languages, i.e., Khmer, Malay, Thai, and Vietnamnese. |
| Subsets | MKQA Khmer (km-KH), MKQA Malay (ms-MY), MKQA Thai (th-TH), MKQA Vietnamnese (vi-VN) |
| Languages | khm, zlm, tha, vie |
| Tasks | Question Answering |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/apple/ml-mkqa |
| HF URL | - |
| Paper URL | https://direct.mit.edu/tacl/article/doi/10.1162/tacl_a_00433/108607/MKQA-A-Linguistically-Diverse-Benchmark-for |

**Comment by fhudi** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @fhudi, may I know the current status of this dataloader creation? Feel free to discuss here if you have any difficulties. Thanks!

**Comment by fhudi** [comment]
@sabilmakbar 
Sorry for the late reply, I am working on it..

**Comment by fhudi** [comment]
@sabilmakbar 
Referring to schema of qa_features, particularly for [documentation on key 'meta'](https://github.com/SEACrowd/seacrowd-datahub/blob/e41f2df95f4a3b6f6e39f8e5c7f4dc60e4d56e59/seacrowd/utils/schemas/qa.py#L23-L24),
the second point seems convoluted, wouldn't it be better to put simple yet straightforward example?

**Comment by fhudi** [comment]
@sabilmakbar 
Hi, I think you missed my point.
Just FYI, I am using the `meta` field as well, thanks for [adding](https://github.com/SEACrowd/seacrowd-datahub/commit/010c6bcc1be55aa59a096b93274cf2974e378892).
Maybe you can add the aforementioned examples to the documentation / commented section of `meta` field.

**Comment by sabilmakbar** [comment]
I was trying to generalize the "how-to" on the 2nd comment that you're referring to (leading to a more abstract and convoluted comment). I'll revise it to improve its brevity and possibly add the example I shared with you in the earlier comment.
