### ISSUE TITLE
Create dataset loader for myParaphrase

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#341]
Dataloader name: `my_paraphrase/my_paraphrase.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?my_paraphrase

|     Dataset| my_paraphrase |
|-------------|---|
| Description | The myParaphrase corpus is intended for the task of assessing whether pairs of Burmese sentences exhibit similar meanings or are paraphrases. It encompasses 40461 pairs for training, along with 1000 pairs for an open test and an additional 1000 pairs for a closed test. If a pair of sentences in Burmese is considered a paraphrase, it is labeled with "1"; if not, they receive a label of "0." |
| Subsets | - |
| Languages | mya |
| Tasks | Paraphrasing |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/ye-kyaw-thu/myParaphrase |
| HF URL | - |
| Paper URL | https://jiist.aiat.or.th/assets/uploads/1667145660263IBU7L25_Deep%20Siamese%20Neural%20Network%20Vs%20Random%20Forest%20for%20Myanmar%20Language%20Paraphrase%20Classification.pdf |

**Comment by djanibekov** [comment]
#self-assign
