### ISSUE TITLE
Create dataset loader for SeaEval

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#342]
Dataloader name: `seaeval/seaeval.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?seaeval

|     Dataset| seaeval |
|-------------|---|
| Description | SeaEval is a benchmark toolkit for evaluating multilingual LLMs. The full SeaEval benchmark contains 28 datasets covering 7 languages. SeaEval introduces 2 new datasets for cross-lingual consistency, each containing parallel questions for the 7 represented languages. SeaEval also introduces 4 new datasets for cultural reasoning (multiple choice Q & A) that are in English but focused on regions including Singapore and the Philipines. |
| Subsets | Cross-MMLU, Cross-LogiQA, SG-Eval, PH-Eval |
| Languages | ind, vie, zlm, fil |
| Tasks | Commonsense Reasoning, Question Answering |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/SeaEval/SeaEval |
| HF URL | https://huggingface.co/datasets/SeaEval/SeaEval_datasets |
| Paper URL | https://arxiv.org/pdf/2309.04766.pdf |

**Comment by raileymontalan** [comment]
#self-assign
