### ISSUE TITLE
Create dataset loader for MUSE (Multilingual Unsupervised and Supervised Embeddings)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#346]
Dataloader name: `muse/muse.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?muse

|     Dataset| muse |
|-------------|---|
| Description | Contains 110 large-scale ground-truth bilingual dictionaries created and released by Meta using an internal translation tool. The dictionaries account for polysemy. The data comprises of a train and test split of 5000 and 1500 unique source words, as well as a larger set of up to 100k pairs. It comprises of Europeans languages in every direction, and SEA languages to and from English. |
| Subsets | - |
| Languages | fil, ind, zlm, tha, vie |
| Tasks | Machine Translation, Word lists |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://github.com/facebookresearch/MUSE#ground-truth-bilingual-dictionaries |
| HF URL | - |
| Paper URL | https://openreview.net/pdf?id=H196sainb |

**Comment by ssun32** [comment]
#self-assign
