### ISSUE TITLE
Create dataset loader for IndoWiki

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#347]
Dataloader name: `indowiki/indowiki.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indowiki

|     Dataset| indowiki |
|-------------|---|
| Description | IndoWiki is a knowledge-graph dataset taken from WikiData and aligned with Wikipedia Bahasa Indonesia as it's corpus. |
| Subsets | - |
| Languages | ind |
| Tasks | Knowledge Base |
| License | MIT (mit) |
| Homepage | https://github.com/IgoRamli/IndoWiki |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/9924844 |

**Comment by zwenyu** [comment]
#self-assign

**Comment by holylovenia** [comment]
> Hi @holylovenia @SamuelCahyawijaya. This dataset only contains entity pairs and its relation w/o any passage information (hence can't be put on `RELATION_EXTRACTION` task). Do you think we should omit the SEACrowd Schema Implementation or proceed to create another task for this? (likely will be using SEACrowd KB)

Will a task using the `pairs` schema be suitable, @zwenyu @sabilmakbar?

**Comment by sabilmakbar** [comment]
In typical KB's format, it comes on a triplet of (Subject/Entity 1, Predicate/Relation, and Object/Entity 2). The difficulty of using pairs is the possibilities of Predicate values can be either unknown -- there could be infinite choices of predicates -- or simply too many classes needs to be defined as `Classlabel` name.

FYI this dataset has 935 possible relations values
<img width="650" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/69744460/1050e03f-5d4f-449a-9602-7c2bac9816aa">

I suggest creating a triplet-based schema which is similar to `pairs` schema, just having all of the columns as string (and possibly we can store both its values and its ID -- if the source dataset has it)

**Comment by zwenyu** [comment]
@holylovenia @sabilmakbar I've added a `triplets` schema and updated the PR. Can you check if it's ok?

**Comment by sabilmakbar** [comment]
> @holylovenia @sabilmakbar I've added a triplets schema and updated the PR. Can you check if it's ok?

I've checked it, and it looks okay (except the config PR should be separated from the dataloader one).

But one thing that worries me is whether we really need this SEACrowd triplet schema for a KB dataset that is less used in LLM/LMM development and evaluation.

**Comment by holylovenia** [comment]
Hello @sabilmakbar @zwenyu, apparently this dataloader utilizes a niche schema, so I think implementing only the `source` schema is enough. No need for the `seacrowd` schema.

**Comment by zwenyu** [comment]
@holylovenia @sabilmakbar Noted. I've reverted the changes and removed the `seacrowd` schema.
