### ISSUE TITLE
Create dataset loader for QASiNa

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#349]
Dataloader name: `qasina/qasina.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?qasina

|     Dataset| qasina |
|-------------|---|
| Description | Question Answering Sirah Nabawiyah Dataset (QASiNa) is Extractive QA Dataset which build to perform QA task in Sirah Nabawiyah domain. |
| Subsets | - |
| Languages | ind |
| Tasks | Question Answering |
| License | MIT (mit) |
| Homepage | https://github.com/rizquuula/QASiNa/blob/main/QASiNa.json |
| HF URL | - |
| Paper URL | https://arxiv.org/pdf/2310.08102.pdf |

**Comment by djanibekov** [comment]
#self-assign
