### ISSUE TITLE
Create dataset loader for Indoler

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#351]
Dataloader name: `indoler/indoler.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indoler

|     Dataset| indoler |
|-------------|---|
| Description | The dataset contains 993 annotated court decision documents. The document was taken from the Decision of the Supreme Court of Indonesia (https://decision3.mahkamahagung.go.id/) for 5 state courts of DKI Jakarta with a total of 1000 criminal documents cases. |
| Subsets | - |
| Languages | ind |
| Tasks | Named Entiy Recognition |
| License | Unknown (unknown) |
| Homepage | https://github.com/ir-nlp-csui/indoler/tree/main |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/abstract/document/9263157 |

**Comment by luckysusanto** [comment]
#self-assign
