### ISSUE TITLE
Create dataset loader for FilWordNet

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#353]
Dataloader name: `filwordnet/filwordnet.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?filwordnet

|     Dataset| filwordnet |
|-------------|---|
| Description | Filipino WordNet (FilWordNet) is a lexical database of Filipino language. It was derived from the Princeton WordNet and translated by humans to Filipino. It documents 13,539 unique words and 9,519 synsets. Each synset includes the definition, part-of-speech, word senses, and Suggested Upper Merged Ontology terms (SUMO terms). |
| Subsets | - |
| Languages | fil |
| Tasks | Wordnet |
| License | Unknown (unknown) |
| Homepage | https://github.com/danjohnvelasco/Filipino-WordNet |
| HF URL | - |
| Paper URL | https://www.researchgate.net/publication/228938676_Introducing_Filipino_WordNet |

**Comment by danjohnvelasco** [comment]
#self-assign
