### ISSUE TITLE
Create dataset loader for Thai Gov v2 Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#357]
Dataloader name: `thai_gov_v2/thai_gov_v2.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?thai_gov_v2

|     Dataset| thai_gov_v2 |
|-------------|---|
| Description | The dataset consists of individual news articles, each corresponding to a unique URL at the Thai government website (https://www.thaigov.go.th/). The dataset structure is as follows: a topic header is followed by the content of the news article, which is then succeeded by a blank line and the source URL |
| Subsets | - |
| Languages | tha |
| Tasks | Language Modeling |
| License | Open Data Commons Public Domain Dedication and License (pddl) |
| Homepage | https://github.com/PyThaiNLP/thaigov-v2-corpus/tree/master/data |
| HF URL | - |
| Paper URL | - |

**Comment by TysonYu** [comment]
#self-assign
