### ISSUE TITLE
Create dataset loader for COPAL

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#36]
Dataloader name: `copal/copal.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?copal

|     Dataset| copal |
|-------------|---|
| Description | a novel Indonesian language common sense reasoning dataset. Unlike the previous Indonesian COPA dataset (XCOPA-ID), COPAL-ID incorporates Indonesian local and cultural nuances, and therefore, provides a more natural portrayal of day-to-day causal reasoning within the Indonesian cultural sphere. Professionally written by natives from scratch, COPAL-ID is more fluent and free from awkward phrases, unlike the translated XCOPA-ID. In addition, we present COPAL-ID in both standard Indonesian and in Jakartan Indonesian–a dialect commonly. It consist of premise, choice1, choice2, question, and label just like COPA dataset. |
| Subsets | test, test_colloquial |
| Languages | ind |
| Tasks | Commonsense Reasoning |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://huggingface.co/datasets/haryoaw/COPAL |
| HF URL | https://huggingface.co/datasets/haryoaw/COPAL |
| Paper URL | https://arxiv.org/pdf/2311.01012v1.pdf |

**Comment by williamnixon20** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @SamuelCahyawijaya , looks like the `_LICENSE` is different from the source repo. The source repo has LICENSE tag of `cc-by-sa-4.0` whereas this submission has license of `cc-by-4.0`, and it can lead to legal implications if this mistach occurs in multiple submissions
