### ISSUE TITLE
Create dataset loader for khPOS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#360]
Dataloader name: `khpos/khpos.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?khpos

|     Dataset| khpos |
|-------------|---|
| Description | khPOS is a POS-tagging dataset for the Khmer language. The data was collected from websites, student and voter lists. It was automatically tokenized with a CRF model and then manually tagged for POS and checked for errors. |
| Subsets | - |
| Languages | khm |
| Tasks | POS Tagging |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/ye-kyaw-thu/khPOS/tree/master |
| HF URL | https://huggingface.co/datasets/seanghay/khPOS |
| Paper URL | https://github.com/ye-kyaw-thu/khPOS/blob/master/khpos.pdf |

**Comment by luckysusanto** [comment]
#self-assign
