### ISSUE TITLE
Create dataset loader for identifikasi-bahasa

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#363]
Dataloader name: `identifikasi_bahasa/identifikasi_bahasa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?identifikasi_bahasa

|     Dataset| identifikasi_bahasa |
|-------------|---|
| Description | The identifikasi-bahasa dataset includes text samples in Indonesian, Ambonese, and Javanese. Each entry is comprised of cleantext, representing the sentence content, and a label identifying the language. The manual input process involved grouping the data by language categories, with labels for language identification and cleantext representing sentence content. The dataset, excluding punctuation and numbers, consists of a minimum of 3,000 Ambonese, 10,000 Javanese, and 3,500 Indonesian language entries, meeting the research's minimum standard for effective language identification. |
| Subsets | - |
| Languages | ind, jav, abs |
| Tasks | Language Identification |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/joanitolopo/identifikasi-bahasa |
| HF URL | - |
| Paper URL | https://ejournal.unkhair.ac.id/index.php/jiko/article/view/2958/2238 |

**Comment by djanibekov** [comment]
#self-assign
