### ISSUE TITLE
Create dataset loader for MEmoLon

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#37]
Dataloader name: `memolon/memolon.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?memolon

|     Dataset| memolon |
|-------------|---|
| Description | MEmoLon is an emotion lexicons for 91 languages, each one covers eight emotional variables and comprises over 100k word entries. There are several versions of the lexicons, the difference being the choice of the expansion model |
| Subsets | - |
| Languages | ind, zlm, tgl, vie, sun, tha, mya, ceb, jav |
| Tasks | Emotion Classification |
| License | MIT (mit) |
| Homepage | https://zenodo.org/record/3756607/files/MTL_grouped.zip?download=1 |
| HF URL | - |
| Paper URL | https://aclanthology.org/2020.acl-main.112.pdf |

**Comment by danjohnvelasco** [comment]
#self-assign

**Comment by danjohnvelasco** [comment]
Hi @SamuelCahyawijaya 👋, what would be the most appropriate seacrowd schema for lexicons like MEmoLon? Currently, it doesn't fit any of the pre-defined SEACrowd schema. 

For context, here's a snippet of the lexicon
![Image](https://github.com/SEACrowd/seacrowd-datahub/assets/54620209/3a43bd2c-6803-4ba9-9325-3b8cbdb4a8be)

Thanks!

**Comment by SamuelCahyawijaya** [comment]
Hi @danjohnvelasco , this is an interesting point.
@holylovenia : Do we need a new schema for this or just implement the source schema as it is not actually a downstream task? IMO, we can just implement the source schema for this

**Comment by danjohnvelasco** [comment]
> Hi @danjohnvelasco , this is an interesting point. @holylovenia : Do we need a new schema for this or just implement the source schema as it is not actually a downstream task? IMO, we can just implement the source schema for this

Thanks for your reply. I agree with implementing just the source schema for this.

**Comment by holylovenia** [comment]
@SamuelCahyawijaya Agree with you. Let's implement just the `source` schema for this dataloader.

@danjohnvelasco Hi Dan, nice to see you here! 👋 Thanks for taking up this dataloader implementation. Feel free to let us know if you have any questions.
