### ISSUE TITLE
Create dataset loader for generated_reviews_enth

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#392]
Dataloader name: `generated_review_enth/generated_review_enth.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?generated_review_enth

|     Dataset| generated_review_enth |
|-------------|---|
| Description | This dataset (referred to as generated_reviews_yn in scb-mt-en-th-2020) are English product reviews generated by CTRL, translated by Google Translate API and annotated as accepted or rejected (correct) based on fluency and adequacy of the translation by human annotators. This allows it to be used for English-to-Thai translation quality esitmation (binary label), machine translation, and sentiment analysis. For SEACrowd, we use data with correct = 1. |
| Subsets | - |
| Languages | tha, eng |
| Tasks | Machine Translation |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/vistec-ai/generated_reviews_enth |
| HF URL | - |
| Paper URL | https://arxiv.org/pdf/2007.03541.pdf |

**Comment by khelli07** [comment]
#self-assign

**Comment by khelli07** [comment]
Working on it now
