### ISSUE TITLE
Create dataset loader for UCLA Phonetic Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#394]
Dataloader name: `ucla_phonetic/ucla_phonetic.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ucla_phonetic

|     Dataset| ucla_phonetic |
|-------------|---|
| Description | This dataset contains audio recordings and phonetic transcriptions of word utterances for various low-resource SEA languages. Each language has a directory of text and audio files, with the latter forming one data subset.  The dataset is prepared from the online UCLA phonetic dataset, which contains 7000 utterances across 100 low-resource languages, phonetically aligned using various automatic approaches, and manually fixed for misalignments. |
| Subsets | - |
| Languages | ace, brv, hil, hni, ilo, khm, mak, mya, pam |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution Non Commercial 2.0 (cc-by-nc-2.0) |
| Homepage | https://github.com/xinjli/ucla-phonetic-corpus?tab=readme-ov-file |
| HF URL | - |
| Paper URL | https://www.cs.cmu.edu/~awb/papers/ICASSP21_Multilingual_Phonetic_Dataset.pdf |

**Comment by ssun32** [comment]
#self-assign
