### ISSUE TITLE
Create dataset loader for TMAD Malay Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#395]
Dataloader name: `tmad_malay_corpus/tmad_malay_corpus.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tmad_malay_corpus

|     Dataset| tmad_malay_corpus |
|-------------|---|
| Description | The Towards Malay Abbreviation Disambiguation (TMAD) Malay Corpus includes sentences from Malay news sites with abbreviations and their meanings. Only abbreviations with more than one possible meaning are included. |
| Subsets | - |
| Languages | zlm |
| Tasks | Word Sense Disambiguation |
| License | Unknown (unknown) |
| Homepage | https://github.com/bhysss/TMAD-CUM/tree/master |
| HF URL | - |
| Paper URL | https://www.researchgate.net/publication/374540148_Towards_Malay_Abbreviation_Disambiguation_Corpus_and_Unsupervised_Model |

**Comment by ssun32** [comment]
#self-assign
