### ISSUE TITLE
Create dataset loader for CrossSum

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#396]
Dataloader name: `crosssum/crosssum.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?crosssum

|     Dataset| crosssum |
|-------------|---|
| Description | This is a large-scale cross-lingual summarization dataset containing article-summary samples in 1,500+ language pairs, which includes pairs with the Burmese, Indonesian and Vietnamese languages. Articles in the first language are assigned summaries in the second language. |
| Subsets | id-my, id-vi, my-id, my-vi, vi-id, vi-my |
| Languages | ind, vie, mya |
| Tasks | Abstractive Summarization |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://drive.google.com/file/d/11yCJxK5necOyZBxcJ6jncdCFgNxrsl4m/view |
| HF URL | https://huggingface.co/datasets/csebuetnlp/CrossSum |
| Paper URL | https://aclanthology.org/2023.acl-long.143.pdf |

**Comment by elyanah-aco** [comment]
#self-assign
