### ISSUE TITLE
Create dataset loader for Malaysia-AI government

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#421]
Dataloader name: `malaysia_ai_government/malaysia_ai_government.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?malaysia_ai_government

|     Dataset| malaysia_ai_government |
|-------------|---|
| Description | This is a dataset containing pdfs scraped from 735 gov.my websites. It consists of thousands of the unedited text, a link to the URL where the website was retrieved, and the name of the pdf. |
| Subsets | gov.my.jsonl, govdocs.jsonl, muftiwp.gov.my.jsonl, myjms.mohe.gov.my.jsonl |
| Languages | zlm |
| Tasks | Language Modeling |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://huggingface.co/datasets/mesolitica/crawl-my-website/resolve/main/gov.my.jsonl |
| HF URL | - |
| Paper URL | - |

**Comment by ilhamfp** [comment]
#self-assign

**Comment by ilhamfp** [comment]
It turns out life gets in the way :) unassigning myself

**Comment by BinWang28** [comment]
#self-assign
