### ISSUE TITLE
Create dataset loader for Malaysia-AI Hansard Scrape

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#423]
Dataloader name: `malaysia_ai_hansard/malaysia_ai_hansard.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?malaysia_ai_hansard

|     Dataset| malaysia_ai_hansard |
|-------------|---|
| Description | The Malaysia AI Hansard Scrape dataset contains 142,766 PDFs from the Malaysian Parliament website (https://www.parlimen.gov.my/hansard-dewan-rakyat.html?uweb=dr). It includes a JSON file for each document with the text labeled "original", page numbers "no_page" and "actual_no_page", the document's "date", and the "url" of the original PDF. |
| Subsets | - |
| Languages | zlm |
| Tasks | Language Modeling |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://huggingface.co/datasets/mesolitica/crawl-malaysian-hansard/resolve/main/hansard.jsonl |
| HF URL | https://huggingface.co/datasets/mesolitica/crawl-malaysian-hansard/resolve/main/hansard.jsonl |
| Paper URL | - |

**Comment by ilhamfp** [comment]
#self-assign

**Comment by ilhamfp** [comment]
It turns out life gets in the way :) unassigning myself

**Comment by BinWang28** [comment]
#self-assign
