### ISSUE TITLE
Create dataset loader for UD Javanese-CSUI

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#427]
Dataloader name: `ud_jv_csui/ud_jv_csui.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ud_jv_csui

|     Dataset| ud_jv_csui |
|-------------|---|
| Description | UD Javanese-CSUI is a dependency treebank in Javanese, a regional language in Indonesia with more than 68 million users. It was developed by Alfina et al. from the Faculty of Computer Science, Universitas Indonesia. The newest version has 1000 sentences and 14K words with manual annotation. |
| Subsets | - |
| Languages | jav |
| Tasks | Dependency Parsing |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/UniversalDependencies/UD_Javanese-CSUI |
| HF URL | - |
| Paper URL | - |

**Comment by fhudi** [comment]
#self-assign
