### ISSUE TITLE
Create dataset loader for Hate Speech Filipino Tweet

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#429]
Dataloader name: `filipino_hatespeech_election/filipino_hatespeech_election.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?filipino_hatespeech_election

|     Dataset| filipino_hatespeech_election |
|-------------|---|
| Description | The dataset used in this study was a subset of the corpus 1,696,613 tweets crawled by Andrade et al. and posted from November 2015 to May 2016 during the campaign period for the Philippine presidential election. They were culled based on the presence of candidate names (e.g., Binay, Duterte, Poe, Roxas, and Santiago) and election-related hashtags (e.g., #Halalan2016, #Eleksyon2016, and #PiliPinas2016).  Data preprocessing was performed to prepare the tweets for feature extraction and classification. It consisted of the following steps: data de-identification, uniform resource locator (URL) removal, special character processing, normalization, hashtag processing, and tokenization. |
| Subsets | - |
| Languages | fil |
| Tasks | Hate Speech Detection |
| License | Unknown (unknown) |
| Homepage | https://huggingface.co/datasets/hate_speech_filipino |
| HF URL | https://huggingface.co/datasets/hate_speech_filipino |
| Paper URL | https://www.researchgate.net/publication/375911232_Hate_Speech_in_Philippine_Election-Related_Tweets_Automatic_Detection_and_Classification_Using_Natural_Language_Processing |

**Comment by chenxwh** [comment]
#self-assign

**Comment by khelli07** [comment]
#self-assign

**Comment by chenxwh** [comment]
hey @khelli07 I have already assigned this a few days ago (see the thread above?) @holylovenia could you take a look if it was not properly linked to me?

**Comment by khelli07** [comment]
Oh I dont know about that, since the Assignee is empty. I thought you were unassigning it. Let me unassign and you can try to assign yourself again.

**Comment by chenxwh** [comment]
#self-assign

**Comment by holylovenia** [comment]
> hey @khelli07 I have already assigned this a few days ago (see the thread above?) @holylovenia could you take a look if it was not properly linked to me?

Sorry, sometimes it doesn't work although there's no error. I think it's something from the github side... It seldom happens but it is a bit concerning.
