### ISSUE TITLE
Create dataset loader for IndoQA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#430]
Dataloader name: `indoqa/indoqa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indoqa

|     Dataset| indoqa |
|-------------|---|
| Description | IndoQA is an Indonesian question-answering dataset. It is comprised of ~4.5k examples. The datasets consists of a context paragraph along with an associated question-answer pair. |
| Subsets | - |
| Languages | ind |
| Tasks | Question Answering |
| License | Creative Commons Attribution No Derivatives 4.0 (cc-by-nd-4.0) |
| Homepage | https://huggingface.co/datasets/jakartaresearch/indoqa |
| HF URL | https://huggingface.co/datasets/jakartaresearch/indoqa |
| Paper URL | https://huggingface.co/datasets/jakartaresearch/indoqa |

**Comment by fhudi** [comment]
#self-assign
