### ISSUE TITLE
Create dataset loader for LEX-INDO: AN INDONESIAN LEXICON

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#437]
Dataloader name: `lex_indo/lex_indo.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?lex_indo

|     Dataset| lex_indo |
|-------------|---|
| Description | This open-source lexicon consists of 2,000 common Indonesian words, with phoneme series attached. |
| Subsets | - |
| Languages | ind |
| Tasks | Lexical Normalization |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://magichub.com/datasets/indonesian-lexicon/ |
| HF URL | - |
| Paper URL | - |

**Comment by joanitolopo** [comment]
#self-assign
