### ISSUE TITLE
Create dataset loader for ASR-IBSC: AN IBAN SPEECH CORPORA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#440]
Dataloader name: `asr_ibsc/asr_ibsc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?asr_ibsc

|     Dataset| asr_ibsc |
|-------------|---|
| Description | This package contains Iban language text and speech suitable for Automatic Speech Recognition (ASR) experiments. In addition, transcribed speech, 2M tokens corpus crawled from an online newspaper site is provided. News data was provided by a local radio station in Sarawak, Malaysia. |
| Subsets | - |
| Languages | iba |
| Tasks | Text-To-Speech Synthesis, Automatic Speech Recognition |
| License | Creative Commons Attribution Share Alike 3.0 (cc-by-sa-3.0) |
| Homepage | https://github.com/sarahjuan/iban |
| HF URL | https://huggingface.co/datasets/meisin123/iban_speech_corpus |
| Paper URL | - |

**Comment by holylovenia** [comment]
Hi @Enliven26, may I know if you need any help with the dataloader?

**Comment by holylovenia** [comment]
Hello @Enliven26! We from SEACrowd are looking forward to using this dataloader in our experiments. Do you think it will be possible for you to proceed with this dataloader's implementation? 😁 We aim to merge it by the end of this week.

**Comment by Enliven26** [comment]
Hello, turn out I don't have time to implement this dataloader. I'm really sorry

**Comment by holylovenia** [comment]
@Enliven26 It's fine, thanks for letting us know. I'm removing your assignment from this issue then. 😁

**Comment by akhdanfadh** [comment]
#self-assign
