### ISSUE TITLE
Create dataset loader for ASR-SMALDUSC: A SCRIPTED MALAY DAILY-USE SPEECH CORPUS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#441]
Dataloader name: `asr_smaldusc/asr_smaldusc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?asr_smaldusc

|     Dataset| asr_smaldusc |
|-------------|---|
| Description | This open-source dataset consists of 4.8 hours of transcribed Malay scripted speech focusing on daily use sentences, where 2,839 utterances contributed by ten speakers were contained. |
| Subsets | - |
| Languages | zlm |
| Tasks | Automatic Speech Recognition, Text-To-Speech Synthesis |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://magichub.com/datasets/malay-scripted-speech-corpus-daily-use-sentence/ |
| HF URL | - |
| Paper URL | - |

**Comment by zwenyu** [comment]
#self-assign
