### ISSUE TITLE
Create dataset loader for Sarawak Malay

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#444]
Dataloader name: `sarawak_malay/sarawak_malay.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?sarawak_malay

|     Dataset| sarawak_malay |
|-------------|---|
| Description | This is a Sarawak Malay conversation data for the purpose of speech technology research. At the moment, this is an experimental data and currently used for investigating speaker diarization. The data was collected by Faculty of Computer Science and Information Technology, Universiti Malaysia Sarawak.  The data consists of 38 conversations that have been transcribed using Transcriber (see TextGrid folder), where each file contains two speakers. Each conversation was recorded by different individuals using microphones from mobile devices or laptops thus, different file formats were collected from the data collectors. All data was then standardized to mono, 16000Khz, wav format. |
| Subsets | - |
| Languages | zlm |
| Tasks | Text-To-Speech Synthesis, Automatic Speech Recognition |
| License | Creative Commons Zero v1.0 Universal (cc0-1.0) |
| Homepage | https://github.com/sarahjuan/sarawakmalay |
| HF URL | - |
| Paper URL | - |

**Comment by djanibekov** [comment]
#self-assign
