### ISSUE TITLE
Create dataset loader for AIFORTHAI - LotusCorpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#449]
Dataloader name: `tha_lotus/tha_lotus.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tha_lotus

|     Dataset| tha_lotus |
|-------------|---|
| Description | The Large vOcabualry Thai continUous Speech recognition (LOTUS) corpus was designed for developing large vocabulary continuous speech recognition (LVCSR), spoken dialogue system, speech dictation, broadcast news transcriber. It contains two datasets, one for training acoustic model, another for training a language model. |
| Subsets | - |
| Languages | tha |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution Non Commercial Share Alike 3.0 (cc-by-nc-sa-3.0) |
| Homepage | https://github.com/korakot/corpus/releases/download/v1.0/AIFORTHAI-LotusCorpus.zip |
| HF URL | - |
| Paper URL | https://doi.org/10.1109/ICSDA.2009.5278377 |

**Comment by djanibekov** [comment]
#self-assign

**Comment by djanibekov** [comment]
unassigned due to university deadlines

**Comment by bp-high** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @holylovenia, can it be used as its homepage?

https://github.com/korakot/corpus/tree/main/LOTUS

Or shall we add the homepage of AI for Thai instead?

**Comment by holylovenia** [comment]
> https://github.com/korakot/corpus/tree/main/LOTUS

@sabilmakbar I think this should be fine as our focus is on the dataset rather than the organization.

**Comment by sabilmakbar** [comment]
Hi sorry, I'm still implementing this, needs a bit more time as this progress of this dataset is ~70% (also found some additional complexity to the dataloader)
