### ISSUE TITLE
Create dataset loader for Okapi m-MMLU

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#476]
Dataloader name: `okapi_m_mmlu/okapi_m_mmlu.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?okapi_m_mmlu

|     Dataset| okapi_m_mmlu |
|-------------|---|
| Description | m-MMLU is a multilingual version of MMLU, a benchmark that measured a text model’s multitask accuracy. The test covers 57 tasks including elementary mathematics, history, computer science, law, and more. |
| Subsets | - |
| Languages | ind, vie |
| Tasks | Commonsense Reasoning |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | http://nlp.uoregon.edu/download/okapi-eval/datasets/ |
| HF URL | https://huggingface.co/datasets/jon-tow/okapi_mmlu |
| Paper URL | https://arxiv.org/abs/2307.16039 |

**Comment by tellarin** [comment]
Back working on this. Sorry for the delay.

**Comment by holylovenia** [comment]
> Back working on this. Sorry for the delay.

Sure, please let us know if you need any help, @tellarin!

**Comment by holylovenia** [comment]
Hi @tellarin, thanks for taking this PR. Just a heads up, due to the delay, I would like to let @SamuelCahyawijaya take over this issue if there's no update until Tuesday, 16 April 2024 EoD AoE (23:59 UTC-12).
