### ISSUE TITLE
Create dataset loader for Aya Collection - Translated

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#480]
Dataloader name: `aya_collection_translated/aya_collection_translated.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?aya_collection_transalated

|     Dataset| aya_collection_translated |
|-------------|---|
| Description | The Aya Collection is a massive multilingual collection consisting of 513 million instances of prompts and completions covering a wide range of tasks. This dataset covers the translated prompts of the Aya Collection. |
| Subsets | Adversarial QA, CNN/DailyMail, dolly, Flan COPA, Flan CoT, Flan GEM Wiki, Flan Lambada, Flan Unified QA, HotpotQA, Joke Explanation, Mintaka, MLQA, NQ-Open, PAWS, PIQA, SODA, Wiki-split, WikiQA, Xlel WD |
| Languages | ceb, tha, mya, zsm, jav, ind, vie, sun, ace, bjn, khm, lao, min |
| Tasks | Chatbot |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://huggingface.co/datasets/CohereForAI/aya_evaluation_suite |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2402.06619 |

**Comment by tellarin** [comment]
Back working on this. Sorry for the delay.

**Comment by muhammadravi251001** [comment]
#self-assign
