### ISSUE TITLE
Create dataset loader for SentiBahasaRojak

### ISSUE THREAD

**Issue by fajri91** [SEACrowd/seacrowd-datahub#497]
Dataloader name: `senti_bahasa_rojak/senti_bahasa_rojak.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?senti_bahasa_rojak

|     Dataset| senti_bahasa_rojak |
|-------------|---|
| Description | This dataset contains reviews for products, movies, and stocks in the Bahasa Rojak dialect, a popular dialect in Malaysia that consists of English, Malay, and Chinese. Each review is manually annotated as positive (bullish for stocks) or negative (bearish for stocks). Reviews are generated through data augmentation using English and Malay sentiment analysis datasets. |
| Subsets | movie, product, stock |
| Languages | zlm, eng, cmn |
| Tasks | Sentiment Analysis |
| License | NA |
| Homepage | https://data.depositar.io/dataset/brcc_and_sentibahasarojak/resource/8a558f64-98ff-4922-a751-0ce2ce8447bd |
| HF URL | - |
| Paper URL | https://aclanthology.org/2022.coling-1.389.pdf |

**Comment by BinWang28** [comment]
#self-assign

**Comment by khelli07** [comment]
#self-assign

**Comment by khelli07** [comment]
WIP today!
