### ISSUE TITLE
Create dataset loader for Tatoeba

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#5]
Dataloader name: `tatoeba/tatoeba.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tatoeba

|     Dataset        | tatoeba  |
|-------------|---|
| Description | Tatoeba is a collection of sentences and translations collected by Tatoeba.org |
| Subsets | tatoeba.ind, tatoeba.jav, tatoeba.tgl, tatoeba.tha, tatoeba.vie |
| Languages | ind, vie, tgl, jav, tha |
| License | Other (other) |
| Homepage | https://tatoeba.org |
| HF URL | https://huggingface.co/datasets/xtreme/ |
| Paper URL | https://tatoeba.org/en/ |

**Comment by IvanHalimP** [comment]
#self-assign

**Comment by IvanHalimP** [comment]
#self-assign

**Comment by IvanHalimP** [comment]
#self-assign

**Comment by ljvmiranda921** [comment]
#self-assign
