### ISSUE TITLE
Create dataset loader for Twitter Corpus of Philippine Englishes (TCOPE)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#50]
Dataloader name: `tcope/tcope.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tcope

|     Dataset| tcope |
|-------------|---|
| Description | This dataset consists of 1,048,576 public tweets (amounting to about 13.5 million words) collected from 13 major cities from the Philippines. Tweets are tagged for part-of-speech and dependency parsing using spaCy. Tweets collected are from 2010 to 2021.  The publicly available dataset is only a random sample (10%) from the whole TCOPE dataset, which consist of roughly 27 million tweets (amounting to about 135 million words) collected from 29 major cities during the same date range. |
| Subsets | TCOPE Public v1 |
| Languages | eng |
| Tasks | Dependency Parsing, POS Tagging |
| License | Creative Commons Zero v1.0 Universal (cc0-1.0) |
| Homepage | https://osf.io/bjzpf |
| HF URL | - |
| Paper URL | https://osf.io/k3qzx |

**Comment by sabilmakbar** [comment]
Hi @elyanah-aco, may I know the current status of this dataloader creation? Feel free to discuss here if you have any difficulties. Thanks!

**Comment by elyanah-aco** [comment]
@sabilmakbar Only got to working on it last week, hope to finish by this week!

**Comment by sabilmakbar** [comment]
Cool, thanks for letting us know! I just want to do some heartbeat check on old issues (somehow the github-actions bot didn't do the job)

**Comment by elyanah-aco** [comment]
@sabilmakbar IMO the POS tagging and dependency parsing on this corpus is not very good. It makes sense though because both were done automatically and many of the entries have code-switching. Do we still implement the diff task schemas despite this?

**Comment by sabilmakbar** [comment]
Thanks for digging into the details of this dataset, @elyanah-aco! I think, it's still okay to implement those tasks despite data constructions and correctness (incl. code-switching). We may add the code-switching information in the desc of this dataset card and dataloader as it's not provided (the automated construction has been mentioned on `using spaCy tagging`).

wdyt, @SamuelCahyawijaya @holylovenia?

**Comment by elyanah-aco** [comment]
Sure! Another note, dependency-parsed and POS-tagged texts follow the same format. That is, it's not really possible to get coreferences/relations/etc for dependency parsing, and `seq_label` schema works better for it IMO. Not really sure how to go about this, wdyt?

**Comment by sabilmakbar** [comment]
Hmm, afaik the dependency parsing should contain relations on the higher level of linguistic units as it's used to infer grammatical relations within a sentence; hence, if that's not possible, we can go without implementing it for now (or we may dig deeper into how the authors used it for dependency parsing).

wdyt, @holylovenia @SamuelCahyawijaya ?

**Comment by sabilmakbar** [comment]
Hi @elyanah-aco, may I know if you have downloaded the datasets from the given link? I haven't been able to check on it yet, but I'd like to ask few qns:
1. Does the dataset look like this for all records?
<img width="869" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/69744460/fb06d41b-8ff6-4400-8e8c-d73451f03a4e">
2. Does the `deptag` field only have 1 `ROOT` tag?
3. Does all the tweets contain only 1 sentences?

If the ans for all these three is yes, we can draw the relations from every token to its root accordingly (hence we can use the `kb` schema as suggested by @holylovenia). Else, we might need to delve in deciding whether we can implement it fully, partially, or none of it.

**Comment by elyanah-aco** [comment]
Hi @sabilmakbar, to answer your questions:

i. Yes
ii. No, there are entries with multiple `ROOT` tags. This tends to occur when the tweet is made up of multiple sentences or repeated symbols/words.
![Image](https://github.com/SEACrowd/seacrowd-datahub/assets/77622465/453fd748-6066-4654-a7b0-022c5773638b)


![Image](https://github.com/SEACrowd/seacrowd-datahub/assets/77622465/7e5adf1b-5559-4a29-a99e-050cea199057)


iii. No

**Comment by sabilmakbar** [comment]
Hi @elyanah-aco, for now let's leave the SEACrowd implementation of dependency parsing for this dataloader and focus on the POS Tagging instead. 

cc @holylovenia @SamuelCahyawijaya

**Comment by holylovenia** [comment]
> Hi @elyanah-aco, for now let's leave the SEACrowd implementation of dependency parsing for this dataloader and focus on the POS Tagging instead.
> 
> cc @holylovenia @SamuelCahyawijaya

Yes. Could you please implement only the `source` schema for the dependency parsing? POS tagging will have both the `source` and `seacrowd` schema.
