### ISSUE TITLE
Create dataset loader for Indonesia Sentiment Analysis Dataset

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#51]
Dataloader name: `id_sentiment_analysis/id_sentiment_analysis.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?id_sentiment_analysis

|     Dataset| id_sentiment_analysis |
|-------------|---|
| Description | This dataset consists of 10806 labeled Indonesian tweets with their corresponding sentiment analysis: positive, negative, and neutral, up to 2019. This dataset was developed in Cloud Experience Research Group, Gadjah Mada University. There is no further explanation of the dataset. Contributor found this dataset after skimming through "Sentiment analysis of Indonesian datasets based on a hybrid deep-learning strategy" (Lin CH and Nuha U, 2023).  See the dataset announcement [here](https://ridi.staff.ugm.ac.id/2019/03/06/indonesia-sentiment-analysis-dataset/). |
| Subsets | - |
| Languages | ind |
| Tasks | Sentiment Analysis |
| License | Unknown (unknown) |
| Homepage | https://github.com/ridife/dataset-idsa/blob/master/Indonesian%20Sentiment%20Twitter%20Dataset%20Labeled.csv |
| HF URL | - |
| Paper URL | https://ridi.staff.ugm.ac.id/2019/03/06/indonesia-sentiment-analysis-dataset/ |

**Comment by faridlazuarda** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @faridlazuarda, may I know the progress on this? If there's no update from your end or comments on this issue (including a request for additional time to work on this) from you in the next 48hrs, we might consider removing this assignment from you so other contributors can work on this issue.

Again, if you find any difficulties in implementing this, pls let us know so we can help you in any way possible. Thanks!

**Comment by reynardryanda** [comment]
Hello @sabilmakbar! if no one is working on this dataset, I would love to try and contribute #self-assign

**Comment by sabilmakbar** [comment]
Gotcha! Apologies for this, @faridlazuarda. Since there's no reply in past 48hrs and someone else is waiting for the update on the status, I'll entrust this issue to another person.

cc @SamuelCahyawijaya @holylovenia

**Comment by sabilmakbar** [comment]
Hi again, @reynardryanda; apologies for the confusion. @faridlazuarda mentioned in other issues assigned for him that he's working on all issues assigned to you in [this reply](https://github.com/SEACrowd/seacrowd-datahub/issues/52#issuecomment-1859878682), but since he isn't replying on all issues assigned, we weren't able to track it. Therefore, I'm reassigning this to him until EoW and see whether he made further updates and/or comments on this task. Else, I'll free this up and assigning it to you

cc @SamuelCahyawijaya @holylovenia

**Comment by sabilmakbar** [comment]
Hi @reynardryanda, I'm assigning you to this bcs previously you wanted to work on this dataloader. Pls unassign yourself if you don't want it anymore. Thanks!

**Comment by Enliven26** [comment]
#self-assign
