### ISSUE TITLE
Create dataset loader for QED

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#512]
Dataloader name: `qed/qed.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?qed

|     Dataset| qed |
|-------------|---|
| Description | QED - The QCRI Educational Domain Corpus (formerly QCRI AMARA Corpus) is an open multilingual collection of subtitles for educational videos and lectures collaboratively transcribed and translated over the AMARA web-based platform. It's developed by Qatar Computing Research Institute, Arabic Language Technologies Group. Along with English, it covers multiple SEA languages, such as vi (Vietnamese), my (Burnmese), jv (Javanese), id (Indonesia), th (Thai), tl (Tagalog), ms (Malaysia). |
| Subsets | - |
| Languages | eng, vie, tha, mya, jav, ind, tgl, zlm |
| Tasks | Machine Translation, Language Modeling |
| License | Other (other) |
| Homepage | https://opus.nlpl.eu/QED/corpus/version/QED |
| HF URL | - |
| Paper URL | https://aclanthology.org/L14-1675/ |

**Comment by patrickamadeus** [comment]
#self-assign
