### ISSUE TITLE
Create dataset loader for CCMatrix

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#514]
Dataloader name: `ccmatrix/ccmatrix.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ccmatrix

|     Dataset| ccmatrix |
|-------------|---|
| Description | The CCMatrix dataset was collected from web crawls and released by Meta. The dataset is constructed based on the margin-based bitext mining which can be applied to monolingual corpora of billions of sentences to produce high quality aligned translation data. |
| Subsets | - |
| Languages | jav, eng, vie, ind, tgl, mya, zlm |
| Tasks | Language Modeling, Machine Translation |
| License | BSD license family (bsd) |
| Homepage | https://opus.nlpl.eu/CCMatrix/corpus/version/CCMatrix |
| HF URL | https://huggingface.co/datasets/yhavinga/ccmatrix |
| Paper URL | https://aclanthology.org/2021.acl-long.507/ |

**Comment by patrickamadeus** [comment]
#self-assign
