### ISSUE TITLE
Create dataset loader for Corpus of Singapore English Messages (CoSEM)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#52]
Dataloader name: `cosem/cosem.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?cosem

|     Dataset| cosem |
|-------------|---|
| Description | The CoSEM dataset consists of over 900,000 lines of online messages from the messaging platform WhatsApp collected from personal chat logs of students enrolled in an advanced sociolinguistics class from the National University of Singapore. Messages collected were from 2016 to 2019.  The dataset is in .txt format, where each line of utterance is tagged with a unique identifier that includes its metadata such as line number, year message was sent, and age and nationality of sender. |
| Subsets | - |
| Languages | eng |
| Tasks | Language Modeling |
| License | Creative Commons Zero v1.0 Universal (cc0-1.0) |
| Homepage | https://github.com/wdwgonzales/CoSEM/blob/main/Corpus/COSEM_v4_publicrelease_SEP172023.zip |
| HF URL | - |
| Paper URL | https://onlinelibrary.wiley.com/doi/full/10.1111/weng.12534 |

**Comment by faridlazuarda** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @faridlazuarda, may I know the progress on this? If there's no update from your end or comments on this issue (including a request for additional time to work on this) from you in the next 48hrs, we might consider removing this assignment from you so other contributors can work on this issue.

Again, if you find any difficulties in implementing this, pls let us know so we can help you in any way possible. Thanks!

**Comment by faridlazuarda** [comment]
@sabilmakbar I have implemented all the dataloaders on my issue, now I'm solving test errors. I will try to clear this until the end of this week.

**Comment by sabilmakbar** [comment]
Hi @faridlazuarda, may we know if all Dataloaders assigned to you have been completed? (incl #49 and #51). Also, what are the issues that you're encountering rn? so that we can discuss them here, resulting in faster deliverables.

I'll wait for your comment until the End of the Week, else we might consider un-assigning it

cc @holylovenia @SamuelCahyawijaya

**Comment by bryanwilie** [comment]
#self-assign

**Comment by bryanwilie** [comment]
Turns out I don't have time this Jan and Feb. Will re-assign later on this or another datasets.

**Comment by Enliven26** [comment]
#self-assign

**Comment by Enliven26** [comment]
#self-assign

**Comment by Enliven26** [comment]
Hi @SamuelCahyawijaya , I need to know which task is language_modeling in the constants.py, thanks

**Comment by Enliven26** [comment]
I still have no idea what is Language Modeling task, couldnt find it in constants.py
