### ISSUE TITLE
Create dataset loader for WikiHow-GOSC

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#526]
Dataloader name: `wikihow_gosc/wikihow_gosc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?wikihow_gosc

|     Dataset| wikihow_gosc |
|-------------|---|
| Description | This dataset consists of wikiHow goal-oriented scripts, or entries with wikiHow goals or tasks, and section/s with steps to perform said tasks. Steps can either be ordered or not. |
| Subsets | ind, tha, vie |
| Languages | ind, tha, vie |
| Tasks | Goal-oriented Generation |
| License | MIT (mit) |
| Homepage | https://github.com/veronica320/wikihow-GOSC/tree/main?tab=readme-ov-file |
| HF URL | - |
| Paper URL | https://aclanthology.org/2021.inlg-1.19v2.pdf |

**Comment by elyanah-aco** [comment]
#self-assign
