### ISSUE TITLE
Create dataset loader for IndoCamRest

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#53]
Dataloader name: `indocamrest/indocamrest.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?indocamrest

|     Dataset| indocamrest |
|-------------|---|
| Description | IndoCamRest is a synthetic task-oriented dialogue system dataset that translated from Cambridge Restaurant 676 (CamRest) dataset (Wen et al., 2016) into the new Indonesian parallel dataset using the translation pipeline method including the delexicalization, translation, and delexicalization. The dataset consists of 676 dialogues in the restaurant reservation domain, with a user and an agent talking to each other to search the restaurant near the user. It also consists of slots and dialogue acts from the user and the agent. |
| Subsets | - |
| Languages | ind |
| Tasks | Dialogue System |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/dehanalkautsar/IndoToD/tree/main/IndoCamRest |
| HF URL | - |
| Paper URL | https://arxiv.org/pdf/2311.00958.pdf |

**Comment by dehanalkautsar** [comment]
#self-assign

**Comment by dehanalkautsar** [comment]
Hi @sabilmakbar, I have a question. As you are aware, this dataset is designed for a dialogue system task. There is also a constant defined for the dialogue system, as mentioned in https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/utils/constants.py#L74. However, when checking https://github.com/SEACrowd/seacrowd-datahub/tree/master/seacrowd/utils/schemas, I couldn't find any schema related to the dialogue system. I've also searched for another dialogue system dataloader, but there is no implementation for the SEACrowd schema (e.g. https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/sea_datasets/cod/cod.py). What do you think I should do about this issue?

**Comment by holylovenia** [comment]
@dehanalkautsar Thanks for the question. Yes, previously we haven't had a specific schema and task to cater to dialogue systems. [I opened an issue and discussion regarding this: #172.](https://github.com/SEACrowd/seacrowd-datahub/issues/172)

**Comment by dehanalkautsar** [comment]
Okay @holylovenia, I’ll be waiting for the update
