### ISSUE TITLE
Create dataset loader for Tatabahasa

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#530]
Dataloader name: `tatabahasa/tatabahasa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tatabahasa

|     Dataset| tatabahasa |
|-------------|---|
| Description | This test is a general test for Malay grammar. Contains 349 questions. |
| Subsets | - |
| Languages | zlm |
| Tasks | Commonsense Reasoning |
| License | Unknown (unknown) |
| Homepage | https://github.com/mesolitica/malaysian-dataset/tree/master/llm-benchmark/tatabahasabm.tripod.com |
| HF URL | - |
| Paper URL | - |

**Comment by patrickamadeus** [comment]
#self-assign
