### ISSUE TITLE
Create dataset loader for XED

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#533]
Dataloader name: `xed/xed.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xed

|     Dataset| xed |
|-------------|---|
| Description | XED, a multilingual fine-grained emotion dataset. The dataset consists of human-annotated Finnish (25k) and English sentences (30k), as well as projected annotations for 30 additional languages, providing new resources for many low-resource languages. |
| Subsets | XED-VI |
| Languages | vie |
| Tasks | Sentiment Analysis |
| License | Unknown (unknown) |
| Homepage | https://github.com/Helsinki-NLP/XED/blob/master/subtitle-retrieval/students/pairs-vi.txt |
| HF URL | - |
| Paper URL | https://aclanthology.org/2020.coling-main.575.pdf |

**Comment by khelli07** [comment]
#self-assign

**Comment by khelli07** [comment]
I think this one has Indonesian as well
https://github.com/Helsinki-NLP/XED/blob/master/subtitle-retrieval/students/pairs-id.txt
Should we include or not?

**Comment by muhammadravi251001** [comment]
#self-assign
