### ISSUE TITLE
Private dataset form URL

### ISSUE THREAD

**Issue by mrqorib** [SEACrowd/seacrowd-datahub#567]
## Describe the bug
I think the link to the private datasheet submission on [this page](https://github.com/SEACrowd/seacrowd-datahub/blob/master/POINTS.md) is wrong. Shouldn't it be https://www.jotform.com/team/232952680898069/seacrowd-paper-with-private-dataset instead of https://www.jotform.com/team/232952680898069/seacrowd-sea-datasets?

**Comment by holylovenia** [comment]
Oh yeah, thanks for noticing!! @mrqorib Could you please open a PR to fix it? I'll approve and merge it ASAP. 😂

**Comment by mrqorib** [comment]
@holylovenia Sure, it's #568. Sorry I don't know what to put in the PR message since it's not a dataloader PR haha. Thanks for your prompt response!

**Comment by holylovenia** [comment]
> @holylovenia Sure, it's #568. Sorry I don't know what to put in the PR message since it's not a dataloader PR haha. Thanks for your prompt response!

Haha, no problem, @mrqorib!! 👍 Done.
