### ISSUE TITLE
Create dataset loader for Myanmar Sign Language Corpus for the Emergency Domain (MSL4Emergency)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#569]
Dataloader name: `msl4emergency/msl4emergency.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?msl4emergency

|     Dataset| msl4emergency |
|-------------|---|
| Description | The MSL4Emergency corpus is part of a larger Myanmar sign language (MSL) corpus that specifically contains sign language videos for the emergency domain. Each signing video is annotated with both its transcription and its Burmese written translation, which may differ from each other due to grammar, syntax and vocabulary differences between MSL and Burmese. Signing videos were made by sign language trainers and deaf trainees. |
| Subsets | - |
| Languages | ysm, mya |
| Tasks | Machine Translation, Sign Language Recognition |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/ye-kyaw-thu/MSL4Emergency/tree/master |
| HF URL | - |
| Paper URL | https://core.ac.uk/reader/489828410 |

**Comment by sabilmakbar** [comment]
#self-assign
