### ISSUE TITLE
Create dataset loader for MinangNLP Sentiment Analysis

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#574]
Dataloader name: `minang_senti/minang_senti.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?minang_senti

|     Dataset| minang_senti |
|-------------|---|
| Description | We release the Minangkabau corpus for sentiment analysis by manually translating 5,000 sentences of Indonesian sentiment analysis corpora. In this work, we conduct a binary sentiment classification on positive and negative sentences by first manually translating the Indonesian sentiment analysis corpus to the Minangkabau language (Agam-Tanah Datar dialect) |
| Subsets | - |
| Languages | ind, min |
| Tasks | Sentiment Analysis |
| License | Unknown (unknown) |
| Homepage | https://github.com/fajri91/minangNLP |
| HF URL | - |
| Paper URL | https://aclanthology.org/2020.paclic-1.17/ |

**Comment by akhdanfadh** [comment]
#self-assign
