### ISSUE TITLE
Create dataset loader for ViMMRC

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#577]
Dataloader name: `vimmrc/vimmrc.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vimmrc

|     Dataset| vimmrc |
|-------------|---|
| Description | ViMMRC, a challenging machine comprehension corpus with multiple-choice questions, intended for research on the machine comprehension of Vietnamese text. This corpus includes 2,783 multiple-choice questions and answers based on a set of 417 Vietnamese texts used for teaching reading comprehension for 1st to 5th graders. |
| Subsets | - |
| Languages | vie |
| Tasks | Commonsense Reasoning |
| License | Unknown (unknown) |
| Homepage | https://sites.google.com/uit.edu.vn/uit-nlp/datasets#h.1qeaynfs79d1 |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/9247161 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
Hi @holylovenia. The [homepage](https://sites.google.com/uit.edu.vn/uit-nlp/datasets#h.1qeaynfs79d1) in datasheet said that I need to
> contact us via email: [kietnv@uit.edu.vn](mailto:kietnv@uit.edu.vn) (Mr. Kiet Nguyen) to sign the corpus user agreement and then receive the corpus.

But from [here](https://sites.google.com/uit.edu.vn/kietnv/datasets#h.1qeaynfs79d1) (the author's blog), the dataset is publicly available. I'm wondering how should I approach this one?

**Comment by holylovenia** [comment]
> Hi @holylovenia. The [homepage](https://sites.google.com/uit.edu.vn/uit-nlp/datasets#h.1qeaynfs79d1) in datasheet said that I need to
> 
> > contact us via email: [kietnv@uit.edu.vn](mailto:kietnv@uit.edu.vn) (Mr. Kiet Nguyen) to sign the corpus user agreement and then receive the corpus.
> 
> But from [here](https://sites.google.com/uit.edu.vn/kietnv/datasets#h.1qeaynfs79d1) (the author's blog), the dataset is publicly available. I'm wondering how should I approach this one?

Let's go with the author's blog for convenience. 😂 Maybe the policy has changed and now it became publicly available.
