### ISSUE TITLE
Create dataset loader for ViCon

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#578]
Dataloader name: `vicon/vicon.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vicon

|     Dataset| vicon |
|-------------|---|
| Description | ViCon comprises pairs of synonyms and antonyms across word classes, thus offering data to distinguish between similarity and dissimilarity. |
| Subsets | - |
| Languages | vie |
| Tasks | Word Analogy |
| License | Creative Commons Attribution Non Commercial Share Alike 2.0 (cc-by-nc-sa-2.0) |
| Homepage | https://www.ims.uni-stuttgart.de/forschung/ressourcen/experiment-daten/vnese-sem-datasets/ |
| HF URL | - |
| Paper URL | https://aclanthology.org/N18-2032/ |

**Comment by muhammadravi251001** [comment]
#self-assign
