### ISSUE TITLE
Create dataset loader for VSoLSCSum

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#580]
Dataloader name: `vsolscsum/vsolscsum.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vsolscsum

|     Dataset| vsolscsum |
|-------------|---|
| Description | The Vietnamese dataset for social context summarization  The dataset contains 141 open-domain articles along with 3,760 sentences, 2,448 extracted standard sentences and comments as standard summaries and 6,926 comments in 12 events. This dataset was manually annotated by human. Note that the extracted standard summaries also include comments. |
| Subsets | - |
| Languages | vie |
| Tasks | Summarization |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/nguyenlab/VSoLSCSum-Dataset |
| HF URL | - |
| Paper URL | https://aclanthology.org/W16-5405/ |

**Comment by muhammadravi251001** [comment]
#self-assign
