### ISSUE TITLE
Create dataset loader for ViLexNorm

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#584]
Dataloader name: `vilexnorm/vilexnorm.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vilexnorm

|     Dataset| vilexnorm |
|-------------|---|
| Description | The ViLexNorm corpus is a collection of comment pairs in Vietnamese, designed for the task of lexical normalization. The corpus contains 10,467 comment pairs, carefully curated and annotated for lexical normalization purposes. These comment pairs are partitioned into three subsets: training, development, and test, distributed in an 8:1:1 ratio. |
| Subsets | - |
| Languages | vie |
| Tasks | Lexical Normalization |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/ngxtnhi/ViLexNorm |
| HF URL | - |
| Paper URL | https://aclanthology.org/2024.eacl-long.85/ |

**Comment by patrickamadeus** [comment]
#self-assign
