### ISSUE TITLE
Create dataset loader for Gowajee Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#586]
Dataloader name: `gowajee/gowajee.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?gowajee

|     Dataset| gowajee |
|-------------|---|
| Description | The Gowajee corpus was collected in the Automatic Speech Recognition class offered at Chulalongkorn University as a homework assignment. Each group was asked to come up with an example smart home application. |
| Subsets | - |
| Languages | tha |
| Tasks | Automatic Speech Recognition |
| License | MIT (mit) |
| Homepage | https://github.com/ekapolc/gowajee_corpus |
| HF URL | - |
| Paper URL | https://github.com/ekapolc/gowajee_corpus?tab=readme-ov-file |

**Comment by akhdanfadh** [comment]
#self-assign
