### ISSUE TITLE
Create dataset loader for MEDISCO

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#591]
Dataloader name: `medisco/medisco.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?medisco

|     Dataset| medisco |
|-------------|---|
| Description | MEDISCO is a Medical Indonesian Speech Corpus. The medical text corpus is collected from five Indonesian online medical consultation websites. From the text corpus, we created a speech corpus that consists of 360 sentences read by 13 speakers. In total, our speech corpus contains 731 medical terms and consists of 4,680 utterances with a total duration of 10 hours. |
| Subsets | Train, Test |
| Languages | ind |
| Tasks | Automatic Speech Recognition |
| License | GNU General Public License v3.0 (gpl-3.0) |
| Homepage | https://huggingface.co/datasets/mrqorib/MEDISCO |
| HF URL | https://huggingface.co/datasets/mrqorib/MEDISCO |
| Paper URL | https://ieeexplore.ieee.org/abstract/document/8629259 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by mrqorib** [comment]
> #self-assign

@akhdanfadh Sorry would you mind giving this to me? This is my dataset 😆

**Comment by mrqorib** [comment]
@akhdanfadh Thanks! 😊
