### ISSUE TITLE
Create dataset loader for XCOPA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#6]
Dataloader name: `xcopa/xcopa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xcopa

|     Dataset| xcopa |
|-------------|---|
| Description | XCOPA: A Multilingual Dataset for Causal Commonsense Reasoning The Cross-lingual Choice of Plausible Alternatives dataset is a benchmark to evaluate the ability of machine learning models to transfer commonsense reasoning across languages. The dataset is the translation and reannotation of the English COPA (Roemmele et al. 2011) and covers 11 languages from 11 families and several areas around the globe. The dataset is challenging as it requires both the command of world knowledge and the ability to generalise to new languages. |
| Subsets | th, id, vi |
| Languages | tha, vie, ind |
| Tasks | Commonsense Reasoning |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/cambridgeltl/xcopa |
| HF URL | https://huggingface.co/datasets/xcopa |
| Paper URL | https://aclanthology.org/2020.emnlp-main.185/ |

**Comment by FawwazMayda** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @FawwazMayda , may I know the current status of this dataloader creation? Feel free to discuss in here if you have any difficulties, thx!

**Comment by FawwazMayda** [comment]
Hi currently continue to do the implementation I will heads up to you again if I found some issues. Thx

**Comment by holylovenia** [comment]
Okay then, @FawwazMayda. Feel free to let us know if you need any help!

**Comment by FawwazMayda** [comment]
I have created the MR: https://github.com/SEACrowd/seacrowd-datahub/pull/286

Kindly need help to review
cc: @sabilmakbar

**Comment by sabilmakbar** [comment]
Hi @FawwazMayda, thanks for submitting a PR to this dataloader. Kindly wait for the reviewing process as it's on a queue now; we'll try to get things done ASAP, so you may create another data loader if there's any in your backlog. Thanks!
