### ISSUE TITLE
Create dataset loader for SEA MADLAD

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#62]
Dataloader name: `sea_madlad/sea_madlad.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?sea_madlad

|     Dataset| sea_madlad |
|-------------|---|
| Description | SEA MADLAD is a subset of MADLAD-400 (Multilingual Audited Dataset: Low-resource And Document-level), which is a document-level multilingual dataset based on Common Crawl. SEA MADLAD only filters the language of the "clean" subset, which covers 36 languages indigenous to SEA from 419 languages in total.   Please note some of SEA lang codes weren't available in this version because those belongs to the languages whose decision was to "remove from its clean version" based on MADLAD auditing process.  MADLAD uses all snapshots of CommonCrawl available as of August 1, 2022. The primary advantage of this dataset over similar datasets is that it is more multilingual, it is audited and more highly filtered, and it is document-level. The main disadvantage is also its strength -- being more filtered, it may lack the recall needed for some applications. |
| Subsets | ace, akb, ban, bbc, bew, bik, btx, ceb, fil, gor, hil, iba, ilo, ind, jav, kac, khm, kxd, lao, mad, mak, meo, min, mkn, msa, msi, mya, nij, nut, pag, shn, sun, tet, tha, vie, war |
| Languages | ace, akb, ban, bbc, bew, btx, ceb, fil, gor, hil, iba, ilo, ind, jav, kac, khm, kxd, lao, mad, mak, meo, min, mkn, msi, mya, nij, nut, pag, shn, sun, tet, tha, vie, war |
| Tasks | Language Modeling, Language Identification |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://huggingface.co/datasets/allenai/MADLAD-400 |
| HF URL | https://huggingface.co/datasets/allenai/MADLAD-400 |
| Paper URL | https://arxiv.org/abs/2309.04662 |

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi, this dataset hasn't been able to be implemented due to limitations in my storage. Will freeing up it after most of the reviewing process has been done
