### ISSUE TITLE
Create dataset loader for VlogQA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#621]
Dataloader name: `vlogqa/vlogqa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vlogqa

|     Dataset| vlogqa |
|-------------|---|
| Description | VlogQA is a Vietnamese spoken language corpus for machine reading comprehension. It consists of 10,076 question-answer pairs based on 1,230 transcript documents sourced from YouTube videos around food and travel. |
| Subsets | - |
| Languages | vie |
| Tasks | Question Answering |
| License | Other (other) |
| Homepage | https://github.com/sonlam1102/vlogqa/tree/main |
| HF URL | - |
| Paper URL | - |

**Comment by akhdanfadh** [comment]
@holylovenia If I may, I want to work on this dataset. But it requires a dataset user agreement. Can I submit on behalf of the SEACrowd organization? I'm also unsure if I can receive the dataset before the dataloader implementation.

**Comment by holylovenia** [comment]
> @holylovenia If I may, I want to work on this dataset. But it requires a dataset user agreement. Can I submit on behalf of the SEACrowd organization? I'm also unsure if I can receive the dataset before the dataloader implementation.

Sure, you can try to submit the user agreement first then we can discuss if you receive the dataset after the dataloader implementation.

**Comment by akhdanfadh** [comment]
I just received the dataset, working on it now.

**Comment by akhdanfadh** [comment]
#self-assign
