### ISSUE TITLE
Create dataset loader for MedEV

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#623]
Dataloader name: `medev/medev.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?medev

|     Dataset| medev |
|-------------|---|
| Description | A high-quality Vietnamese-English parallel dataset constructed specifically for the medical domain, comprising approximately 360K sentence pairs |
| Subsets | - |
| Languages | vie |
| Tasks | Machine Translation |
| License | Unknown (unknown) |
| Homepage | https://huggingface.co/datasets/nhuvo/MedEV |
| HF URL | https://huggingface.co/datasets/nhuvo/MedEV |
| Paper URL | - |

**Comment by patrickamadeus** [comment]
#self-assign
