### ISSUE TITLE
Create dataset loader for UIT-ViSFD

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#627]
Dataloader name: `uit_visfd/uit_visfd.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit_visfd

|     Dataset| uit_visfd |
|-------------|---|
| Description | UIT-ViSFD is the Vietnamese Smartphone Feedback Dataset. It is an aspect-based sentiment analysis dataset. It consists of 11,122 human-annotated comments for mobile e-commerce. |
| Subsets | - |
| Languages | vie |
| Tasks | Aspect Based Sentiment Analysis |
| License | Unknown (unknown) |
| Homepage | https://github.com/LuongPhan/UIT-ViSFD |
| HF URL | - |
| Paper URL | - |

**Comment by muhammadravi251001** [comment]
#self-assign
