### ISSUE TITLE
Create dataset loader for Myanmar (Burmese) Name Romanization with Alignment on Grapheme-Level

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#64]
Dataloader name: `burmese_romanize/burmese_romanize.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?burmese_romanize

|     Dataset| burmese_romanize |
|-------------|---|
| Description | This dataset consists of 2,335 Burmese names from real university students and faculty, public figures, and minorities from Myanmar. Each entry includes the original name in Burmese script, its corresponding Romanization, and the aligned Burmese and Latin graphemes. |
| Subsets | - |
| Languages | mya |
| Tasks | Machine Translation |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | http://www.nlpresearch-ucsy.edu.mm/NLP_UCSY/name-db.html |
| HF URL | - |
| Paper URL | https://att-astrec.nict.go.jp/member/ding/NLP2017-P5-7.pdf |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
What should be the task for this? @SamuelCahyawijaya @holylovenia 

For context, the data are organized in the following format, while the alignment is completely monotonic and one-to-one.
[original Myanmar name] ||| [original Romanization] ||| [aligned Myanmar/Latin graphemes]
e.g. `ဂျာနွယ်ကော့ ||| Ja Noi Kaw ||| ဂျ/J ာ/a န/N ွယ်/oi က/K ော/aw ့/@`

**Comment by holylovenia** [comment]
Hi @akhdanfadh, may I know if you are still working on this issue? Please let @holylovenia @SamuelCahyawijaya @sabilmakbar know if you need any help.
