### ISSUE TITLE
Create dataset loader for Filipino Hate Speech Tiktok - Text

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#65]
Dataloader name: `filipino_hatespeech_tiktok/filipino_hatespeech_tiktok.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?filipino_hatespeech_tiktok

|     Dataset| filipino_hatespeech_tiktok |
|-------------|---|
| Description | The dataset contains annotated hate speech from transcribed Tiktok videos, mostly in Taglish (codemixed Tagalog and Cebuano) collected via an unofficial Tiktok API. Most of the domain and context of the videos are related to politics and general elections in the Philippines.  Labeling: 0 - no hate speech, 1 - recognized hate speech |
| Subsets | - |
| Languages | tgl, eng |
| Tasks | Hate Speech Detection |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/imperialite/filipino-tiktok-hatespeech/ |
| HF URL | - |
| Paper URL | https://dl.acm.org/doi/abs/10.1145/3485768.3485806 |

**Comment by williamnixon20** [comment]
#self-assign
