### ISSUE TITLE
Create dataset loader for Filipino Gay Language (Swardspeak)

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#66]
Dataloader name: `filipino_gay_lang/filipino_gay_lang.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?filipino_gay_lang

|     Dataset| filipino_gay_lang |
|-------------|---|
| Description | The dataset contains 4000+ Filipino tweets in gay language or lingo also called swardspeak in slang terminology. The tweet dataset was collected from February 2013 to November 2014 using the following commonly used gay words as filters:  jinet ("hot"), ditey ("here"), imbyerna ("annoying"), etc. The original paper makes use of the corpus to develop a gay language translator to understand the meaning of phrases using gay words in Filipino. |
| Subsets | - |
| Languages | fil |
| Tasks | Language Modeling |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/imperialite/Philippine-Languages-Online-Corpora/tree/master/Tweets/Gay%20language |
| HF URL | - |
| Paper URL | https://national-u.edu.ph/wp-content/uploads/2016/08/Witchebelles-Anata-Magcharot-kay-Mudra-na-Nagsusuba-si-Akech-Developing-a-Rule-based-Unidirectional-Beki-Lingo-to-Filipino-Translator.pdf |

**Comment by ilhamfp** [comment]
I checked the data, and it seems incomplete.. https://github.com/imperialite/Philippine-Languages-Online-Corpora/tree/master/Tweets/Gay%20language

There is are English counterpart for the Tagalog messages.

**Comment by sabilmakbar** [comment]
Since the Github Repo owner also contributes to SEACrowd, why don't we ask it directly?

pinging @imperialite and @ilhamfp

**Comment by imperialite** [comment]
Hi all. Yup, beki words, gay lingo, and swardspeak can be interchanged. Swardspeak and beki words are just slangs for gay lingo. 

I think it's safe to label the dataset as Filipino if we require just one. Filipino tend to have mixed Tagalog and English words which is evident in the dataset.

**Comment by imperialite** [comment]
I saw that I put Tagalog and English for this dataset. It should be Filipino only. Sorry for this, how can I change it?

**Comment by SamuelCahyawijaya** [comment]
Hi @imperialite, thank you for letting us know about it. I have updated the language on the issue description and the datasheet information. 🙏🏻

**Comment by sabilmakbar** [comment]
Hi @ilhamfp, since the blocker regarding ambiguity for this dataset has been resolved, do you want to self-assign it?

**Comment by mrafifrbbn** [comment]
#self-assign

**Comment by mrafifrbbn** [comment]
Hi,

Yes, I am still working on it. Please give me 2 weeks to finish. Thank you.
