### ISSUE TITLE
Create dataset loader for Myanmar Part-of-Speech (myPOS) v3.0

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#67]
Dataloader name: `mypos_v3/mypos_v3.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mypos_v3

|     Dataset| mypos_v3 |
|-------------|---|
| Description | This version of the myPOS corpus extends the original myPOS corpus from 11,000 to 43,196 Burmese sentences by adding data from the ASEAN MT NECTEC corpus and two developed parallel corpora (Myanmar-Chinese and Myanmar-Korean). The original 11,000 sentences were collected from Wikipedia and includes various topics such as economics, history, news, politics and philosophy.  The format used in the corpus is `word/POS-tag`, and the pipe delimiter "|" is used to separate word-tag pairs per segment in compound words.  All new raw sentences were manually segmented. POS tagging was both done manually and with the RDRPOS tagger and manually checked for errors. |
| Subsets | - |
| Languages | mya |
| Tasks | POS Tagging |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/ye-kyaw-thu/myPOS/tree/master/corpus-ver-3.0 |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/9376835 |

**Comment by ljvmiranda921** [comment]
#self-assign
