### ISSUE TITLE
Create dataset loader for CUB Bahasa

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#68]
Dataloader name: `cub_bahasa/cub_bahasa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?cub_bahasa

|     Dataset| cub_bahasa |
|-------------|---|
| Description | Semi-translated dataset of CUB-200-2011 into Indonesian. This dataset contains thousands of image-text annotation pairs of 200 subcategories belonging to birds. The natural language descriptions are collected through the Amazon Mechanical Turk (AMT) platform and are required at least 10 words, without any information on subcategories and actions. |
| Subsets | - |
| Languages | ind |
| Tasks | Image-to-Text Generation |
| License | Unknown (unknown) |
| Homepage | https://github.com/share424/Indonesian-Text-to-Image-synthesis-with-Sentence-BERT-and-FastGAN/tree/master |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2303.14517 |

**Comment by akhdanfadh** [comment]
#self-assign
