### ISSUE TITLE
Create dataset loader for XStoryCloze

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#69]
Dataloader name: `xstorycloze/xstorycloze.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xstorycloze

|     Dataset| xstorycloze |
|-------------|---|
| Description | XStoryCloze consists of the professionally translated version of the English StoryCloze dataset (Spring 2016 version) to 10 non-English languages. This dataset is released by Meta AI. |
| Subsets | id, my |
| Languages | ind, mya |
| Tasks | Commonsense Reasoning |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://huggingface.co/datasets/juletxara/xstory_cloze |
| HF URL | https://huggingface.co/datasets/juletxara/xstory_cloze |
| Paper URL | https://aclanthology.org/2022.emnlp-main.616 |

**Comment by williamnixon20** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @SamuelCahyawijaya, can we remove Tasks of Language Modelling from this one? Since there's no explicit mention of LangMod use case for this dataset.

**Comment by SamuelCahyawijaya** [comment]
@sabilmakbar : sorry for the late reply. Yes, exactly, we can remove the LangMod task from the list. Sorry for the confusion.

**Comment by sabilmakbar** [comment]
Hi @SamuelCahyawijaya , can we revise this to `COMMONSENSE_REASONING`?
