### ISSUE TITLE
Create dataset loader for MABL

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#70]
Dataloader name: `mabl/mabl.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mabl

|     Dataset| mabl |
|-------------|---|
| Description | The MABL (Metaphors Across Borders and Languages) dataset is a collection of 6,366 figurative language expressions from seven languages, crafted to improve multilingual models' understanding of figurative speech and its linguistic variations. It was built by crowdsourcing native speakers to generate paired metaphors that began with the same words but had different meanings, as well as the literal interpretations of both phrases. Each expression was checked by fluent speakers to ensure they were clear, appropriate, and followed the format, discarding any that didn't meet these standards. |
| Subsets | ind, jav, sun |
| Languages | ind, jav, sun |
| Tasks | Question Answering |
| License | MIT (mit) |
| Homepage | https://github.com/simran-khanuja/Multilingual-Fig-QA |
| HF URL | https://huggingface.co/datasets/dbarbedillo/SMS_Spam_Multilingual_Collection_Dataset |
| Paper URL | https://aclanthology.org/2023.findings-acl.525 |

**Comment by ljvmiranda921** [comment]
#self-assign
