### ISSUE TITLE
Create dataset loader for MASSIVE

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#71]
Dataloader name: `massive/massive.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?massive

|     Dataset| massive |
|-------------|---|
| Description | MASSIVE dataset—Multilingual Amazon Slu resource package (SLURP) for Slot-filling, Intent classification, and Virtual assistant Evaluation. MASSIVE contains 1M realistic, parallel, labeled virtual assistant utterances spanning 18 domains, 60 intents, and 55 slots. MASSIVE was created by tasking professional translators to localize the English-only SLURP dataset into 50 typologically diverse languages, including 8 native languages and 2 other languages mostly spoken in Southeast Asia. |
| Subsets | id-ID, jv-ID, km-KH, ms-MY, my-MM, th-TH, tl-PH, vi-VN |
| Languages | ind, jav, khm, zlm, mya, tha, tgl, vie, cmn, tam |
| Tasks | Slot Filling, Intent Classification |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/alexa/massive |
| HF URL | https://huggingface.co/datasets/qanastek/MASSIVE |
| Paper URL | https://aclanthology.org/2023.acl-long.235/ |

**Comment by holylovenia** [comment]
#self-assign

**Comment by yana-xuyan** [comment]
#self-assign

**Comment by yana-xuyan** [comment]
Hi @holylovenia @SamuelCahyawijaya @sabilmakbar, I just found that the authors have also released MASSIVE 1.1 version of the dataset on Nov. 28 (before it was MASSIVE 1.0). Should we make another data loader for MASSIVE 1.1?

**Comment by sabilmakbar** [comment]
Yeah you may implement for the newest one (no need to implement its earlier version). You just have to define `SOURCE_VERSION` as `1.1`.

**Comment by yana-xuyan** [comment]
Okie, sounds great!
