### ISSUE TITLE
Create dataset loader for Yunshan-Cup-2020 Lao POS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#79]
Dataloader name: `yunshan_cup_2020/yunshan_cup_2020.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?yunshan_cup_2020

|     Dataset| yunshan_cup_2020 |
|-------------|---|
| Description | Lao POS dataset containing 11,000 sentences was released as part of Yunshan-Cup-2020 evaluation track. |
| Subsets | lao |
| Languages | lao |
| Tasks | POS Tagging |
| License | Unknown (unknown) |
| Homepage | https://github.com/GKLMIP/Yunshan-Cup-2020 |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2204.02658 |

**Comment by jen-santoso** [comment]
#self-assign
