### ISSUE TITLE
Create dataset loader for MTOP

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#81]
Dataloader name: `mtop/mtop.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mtop

|     Dataset| mtop |
|-------------|---|
| Description | An almost-parallel multilingual task-oriented semantic parsing dataset covering 6 languages and 11 domains. This is the first multilingual dataset which contains compositional representations that allow complex nested queries. |
| Subsets | Domain, Intent |
| Languages | tha |
| Tasks | Constituency Parsing, Semantic Role Labeling, Intent Classification |
| License | Unknown (unknown) |
| Homepage | https://huggingface.co/datasets/mteb/mtop_domain, https://huggingface.co/datasets/mteb/mtop_intent |
| HF URL | https://huggingface.co/datasets/mteb/mtop_domain, https://huggingface.co/datasets/mteb/mtop_intent |
| Paper URL | https://arxiv.org/abs/2008.09335 |

**Comment by elyanah-aco** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @elyanah-aco, may I know the current status of this dataloader creation? Feel free to discuss here if you have any difficulties. Thanks!

**Comment by elyanah-aco** [comment]
@sabilmakbar Still working on my other 2 dataloaders, will get to this once those are done

**Comment by sabilmakbar** [comment]
Cool, thanks for letting us know! Please take your time working w/ other dataloaders first and let us know if you find any roadblocks!

**Comment by elyanah-aco** [comment]
Hi @sabilmakbar, what should I do if there are two subsets with different labels for the same schema (`domain` and `intent` under `text` schema)?
