### ISSUE TITLE
Create dataset loader for CulturaX

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#84]
Dataloader name: `culturax/culturax.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?culturax

|     Dataset| culturax |
|-------------|---|
| Description | CulturaX is a comprehensive multilingual dataset comprising 6.3 trillion tokens across 167 languages, designed for large language model development. It incorporates an advanced cleaning and deduplication process, including language identification and fuzzy deduplication with MinHash, to ensure high-quality data for model training. The dataset, which spans 16TB in parquet format and 27TB when unpacked, is a combination of the latest mC4 and OSCAR corpora, emphasizing non-English languages to support multilingual model training. For data cleaning validation, CulturaX employs a SentencePiece tokenizer and KenLM language models, utilizing recent Wikipedia dumps for perplexity scoring. |
| Subsets | id, jv, km, lo, tl, min, my, su, th, vi, ms, ceb, war, cbk, bcl |
| Languages | ind, jav, khm, lao, tgl, min, mya, sun, tha, vie, zlm, ceb, war, cbk, bcl |
| Tasks | Language Modeling |
| License | Other (other) |
| Homepage | https://huggingface.co/datasets/uonlp/CulturaX |
| HF URL | https://huggingface.co/datasets/uonlp/CulturaX |
| Paper URL | https://arxiv.org/abs/2309.09400 |

**Comment by akhdanfadh** [comment]
#self-assign
