### ISSUE TITLE
Create dataset loader for GlotStoryBook

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#91]
Dataloader name: `glotstorybook/glotstorybook.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?glotstorybook

|     Dataset| glotstorybook |
|-------------|---|
| Description | The GlotStoryBook dataset is a compilation of children's storybooks from the Global Storybooks project, encompassing 174 languages organized for machine translation tasks. It features rows containing the text segment (text number), the language code, and the file name, which corresponds to the specific book and story segment. This structure allows for the comparison of texts across different languages by matching file names and text numbers between rows. |
| Subsets | khg, khm, mya, tet, tha, vie |
| Languages | khg, khm, mya, tet, tha, vie |
| Tasks | Language Modeling |
| License | Other (other) |
| Homepage | https://huggingface.co/datasets/cis-lmu/GlotStoryBook |
| HF URL | https://huggingface.co/datasets/cis-lmu/GlotStoryBook |
| Paper URL | https://arxiv.org/abs/2310.16248 |

**Comment by akhdanfadh** [comment]
#self-assign
