### ISSUE TITLE
Create dataset loader for MultiJail

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#92]
Dataloader name: `xl_jailbreak/xl_jailbreak.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xl_jailbreak

|     Dataset| xl_jailbreak |
|-------------|---|
| Description | The MultiJail dataset is the first of its kind, focusing on multilingual jailbreak scenarios. It includes 315 English harmful queries, each translated into nine different languages by native speakers, covering both high and low-resource languages. To ensure accuracy, a subset of these translations is reviewed by a separate group of native speakers. |
| Subsets | - |
| Languages | jav, vie, tha |
| Tasks | Language Modeling |
| License | MIT (mit) |
| Homepage | https://github.com/DAMO-NLP-SG/multilingual-safety-for-LLMs |
| HF URL | https://huggingface.co/datasets/DAMO-NLP-SG/MultiJail |
| Paper URL | https://arxiv.org/abs/2310.06474 |

**Comment by akhdanfadh** [comment]
#self-assign

**Comment by akhdanfadh** [comment]
Btw, this dataset focuses on jailbreaking, and I'm uncertain whether the task should be categorized as Language Modeling aka `Tasks.SELF_SUPERVISED_PRETRAINING`.

I'm leaning more towards `Tasks.MACHINE_TRANSLATION` since the dataset has been manually annotated and is, therefore, of high quality.

What are your thoughts? Alternatively, should I create a new task, though I'm not sure about the schema for this?

@holylovenia @SamuelCahyawijaya

**Comment by holylovenia** [comment]
Hi @akhdanfadh, thanks for the question! Based on @sabilmakbar, @SamuelCahyawijaya, you, and I's discussion in Discord, we can use `Tasks.PROMPTING` (#138) for this.

**Comment by akhdanfadh** [comment]
I'll work on all my assigned dataloaders this weekend.

**Comment by holylovenia** [comment]
Okay then, @akhdanfadh. Feel free to let us know if you need any help!

**Comment by sabilmakbar** [comment]
Hi @akhdanfadh, may I know the progress of this dataloader creation? Since it has passed 2+2 weeks of expected completion of dataloader, I will clear the assignee if no update is received by Monday 12 PM UTC.

**Comment by bryanwilie** [comment]
#self-assign

**Comment by bryanwilie** [comment]
Turns out I don't have time this Jan and Feb. Will re-assign later on this or another datasets.

**Comment by Enliven26** [comment]
#self-assign
