### ISSUE TITLE
Create dataset loader for Khmer ALT POS

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#93]
Dataloader name: `khmer_alt_pos/khmer_alt_pos.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?khmer_alt_pos

|     Dataset| khmer_alt_pos |
|-------------|---|
| Description | The data contains 20,000-sentence Khmer corpus with manual tokenization and POS-tagging annotation. |
| Subsets | - |
| Languages | khm |
| Tasks | POS Tagging |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/km-nova-181101.zip |
| HF URL | - |
| Paper URL | https://dl.acm.org/doi/10.1145/3464378 |

**Comment by muhsatrio** [comment]
#self-assign
