### ISSUE TITLE
Create dataset loader for LimeSoda

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#96]
Dataloader name: `limesoda/limesoda.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?limesoda

|     Dataset| limesoda |
|-------------|---|
| Description | Thai fake news dataset in the healthcare domain consisting of curate and manually annotated 7,191 documents (only 4,141 documents contain token labels and are used as a test set of the baseline models). Each document in the dataset is classified as fact, fake, or undefined. |
| Subsets | - |
| Languages | tha |
| Tasks | Text Classification |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://github.com/byinth/LimeSoda |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/9678187 |

**Comment by jen-santoso** [comment]
#self-assign
