### ISSUE TITLE
Create dataset loader for Inter-Agency Task Force for the Management of Emerging Infectious Diseases (IATF) COVID-19 Resolutions

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#97]
Dataloader name: `iatf/iatf.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?iatf

|     Dataset| iatf |
|-------------|---|
| Description | This dataset contains 65 resolutions about the COVID-19 pandemic from January 1 to July 30, 2020 made by the Philippine IATF, a task force organized to respond to affairs regarding emerging infectious diseases in the country. Each resolution or subset is split into lines, which are categorized based on what section they belong to (heading, preamble, operative, endorsement). Each subset is saved as an .rda file. |
| Subsets | iatfResolution52, iatfResolution20, iatfResolution46A, iatfResolution35, iatfResolution01, iatfResolution56, iatfResolution33, iatfResolution09, iatfResolution40, iatfResolution39, iatfResolution21, iatfResolution10, iatfResolution44, iatfResolution43, iatfResolution08, iatfResolution22, iatfResolution51, iatfResolution23, iatfResolution58, iatfResolution36, iatfResolution32, iatfResolution11, iatfResolution60A, iatfResolution27, iatfResolution53, iatfResolution19, iatfResolution30, iatfResolution48, iatfResolution47, iatfResolution59, iatfResolution38, iatfResolution14, iatfResolution03, iatfResolution31, iatfResolution15, iatfResolution12, iatfResolution60, iatfResolution50A, iatfResolution26, iatfResolution57, iatfResolution41, iatfResolution07, iatfResolution25, iatfResolution30A, iatfResolution02, iatfResolution55, iatfResolution55A, iatfResolution29, iatfResolution24, iatfResolution42, iatfResolution05, iatfResolution46, iatfResolution54, iatfResolution34, iatfResolution37, iatfResolution45, iatfResolution04, iatfResolution28, iatfResolution17, iatfResolution49, iatfResolution18, iatfResolution06, iatfResolution50, iatfResolution13, iatfResolution16, iatfGuidelineOmnibus |
| Languages | fil |
| License | GNU General Public License v3.0 (gpl-3.0) |
| Homepage | https://github.com/como-ph/covidphtext/tree/master/data |
| HF URL | - |
| Paper URL | https://como-ph.github.io/post/creating-text-data-from-iatf-resolutions/ |

**Comment by SamuelCahyawijaya** [comment]
I use this snippet to check the data size, perhaps it can be used for implementing the dataloader as well.
```
import glob
import pyreadr

for path in glob.glob('iatfR*.rda') + glob.glob('iatfG*.rda'):
    result = pyreadr.read_r(path)
    df = result[list(result.keys())[0]] # extract the pandas data frame for object df1
```

**Comment by ilhamfp** [comment]
#self-assign

**Comment by ilhamfp** [comment]
What schema/task would this falls into? Self-supervised pretraining?

**Comment by ilhamfp** [comment]
Currently working a PR :)

**Comment by holylovenia** [comment]
Okay then, @ilhamfp. Feel free to let us know if you need any help! Thanks for the response.

**Comment by ilhamfp** [comment]
Worked on 4 other PRs the past few weeks. Will work on this soon.

**Comment by sabilmakbar** [comment]
Not sure why the task type doesn't appear in the issue ticket. From the [excel catalogue](https://docs.google.com/spreadsheets/d/1ibbywsC1tQ_sLPX8bUAjC-vrTrUqZgZA46W_sxWw4Ss/edit#gid=1205522615), it falls under Language Modeling task

**Comment by holylovenia** [comment]
> Worked on 4 other PRs the past few weeks. Will work on this soon.

Thanks for updating us. Please let us know if you need any help.

**Comment by ilhamfp** [comment]
#self-assign

Sorry forgot about this one. Sending the PR right now :)
